/* CoBook LOYALTY — самостоятельный MODULE */
(function(){
 const K={programs:'cobook_loyalty_programs',accounts:'cobook_loyalty_accounts',depositPrograms:'cobook_deposit_programs',deposits:'cobook_loyalty_deposits',referrals:'cobook_referrals',certificates:'cobook_certificates',subscriptions:'cobook_subscriptions'};
 const read=(k,f=[])=>{try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch(_){return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),arr=v=>Array.isArray(v)?v:[],esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'),money=v=>`${Number(v||0).toLocaleString('ru-RU')} ₽`,clients=()=>read('cobook_clients',[]),procedures=()=>read('cobook_procedures',[]);
 const back=t=>`<button class="section-back-button" data-action="loyalty-back" data-target="${t}" type="button">Назад</button>`;
 function head(k,t){return `<section class="page-head"><div class="eyebrow">${k}</div><h1>${t}</h1></section>`}
 function home(){return `<section class="page-head"><div class="eyebrow">НАСТРОЙКИ · ЛОЯЛЬНОСТЬ</div><h1>Лояльность</h1></section><div class="loyalty-menu">${[['programs','Программы','Скидки, подарки и награды'],['certificates','Сертификаты','Предоплаченные сертификаты'],['subscriptions','Абонементы','Пакеты посещений или услуг'],['referrals','Реферальная программа','Вознаграждение за приглашения'],['accounts','Личный счёт','Баланс и операции'],['deposits','Депозиты','Предоплата с условиями и сроком']].map(([id,t,d])=>`<button class="management-folder loyalty-menu-card" data-action="loyalty-section" data-section="${id}" type="button"><span class="management-folder-icon">${id==='deposits'?'◈':id==='accounts'?'₽':id==='referrals'?'↗':id==='subscriptions'?'▤':id==='certificates'?'◇':'◎'}</span><span><b>${t}</b><small>${d}</small></span><span class="management-chevron">›</span></button>`).join('')}</div>${back('settings')}`}
 function programs(){const a=read(K.programs,[]);return `${head('ЛОЯЛЬНОСТЬ · ПРОГРАММЫ','Программы')}<div class="loyalty-list">${a.length?a.map((p,i)=>`<button class="loyalty-card" data-action="program-edit" data-index="${i}" type="button"><span><b>${esc(p.name)}</b><small>${p.condition==='spent'?`Сумма ${p.threshold}`:`${p.threshold} посещений`} · ${p.reward==='free'?'Бесплатно':p.reward==='money'?`Деньги ${money(p.money)}`:`Скидка ${p.discount}%`}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Программ пока нет</div>'}</div><button class="primary full service-add" data-action="program-create" type="button">Создать программу</button>${back('programs')}`}
 function rewardFields(p){if(p.reward==='money')return `<label class="service-field"><span>Сумма</span><input data-p="money" type="number" min="1" value="${esc(p.money||500)}"><small>₽</small></label>`;if(p.reward==='free'){const ps=procedures();return `<div class="loyalty-subblock"><b>Что дарится бесплатно?</b><label><input type="radio" name="free-mode" data-p="freeMode" value="procedure" ${p.freeMode!=='manual'?'checked':''}> Процедура</label><label><input type="radio" name="free-mode" data-p="freeMode" value="manual" ${p.freeMode==='manual'?'checked':''}> Другое</label><label class="service-field"><span>Процедура</span><select data-p="freeProcedureIndex"><option value="">Выберите процедуру</option>${ps.map((x,i)=>`<option value="${i}" ${String(p.freeProcedureIndex)===String(i)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label><label class="service-field"><span>Что дарите</span><input data-p="freeManual" value="${esc(p.freeManual||'')}" placeholder="Например, шампунь"></label></div>`}return `<label class="service-field"><span>Размер скидки</span><input data-p="discount" type="number" min="0" max="100" value="${esc(p.discount??20)}"><small>%</small></label>`}
 function programEditor(i=null){const a=read(K.programs,[]),p=i===null?{name:'',condition:'visits',threshold:10,reward:'discount',discount:20,freeMode:'procedure',freeProcedureIndex:'',freeManual:'',money:500,scope:'all'}:{...a[i]};return `${head('ЛОЯЛЬНОСТЬ · ПРОГРАММА',i===null?'Новая программа':'Изменить программу')}<section class="loyalty-form"><label class="service-field"><span>Название программы</span><input data-p="name" value="${esc(p.name)}" placeholder="Каждая 10-я стрижка"></label><div class="loyalty-block"><b>Условие</b><label class="service-field"><span>Событие</span><select data-p="condition"><option value="visits" ${p.condition==='visits'?'selected':''}>Количество посещений</option><option value="spent" ${p.condition==='spent'?'selected':''}>Сумма покупок</option></select></label><label class="service-field"><span>Значение</span><input data-p="threshold" type="number" min="1" value="${esc(p.threshold)}"></label></div><div class="loyalty-block"><b>Награда</b><label class="service-field"><span>Тип</span><select data-p="reward"><option value="discount" ${p.reward==='discount'?'selected':''}>Скидка, %</option><option value="free" ${p.reward==='free'?'selected':''}>Бесплатно</option><option value="money" ${p.reward==='money'?'selected':''}>Деньги</option></select></label><div>${rewardFields(p)}</div></div><label class="service-field"><span>Для кого</span><select data-p="scope"><option value="all" ${p.scope==='all'?'selected':''}>Всех клиентов</option><option value="selected" ${p.scope==='selected'?'selected':''}>Выбранных клиентов</option></select></label><button class="primary full" data-action="program-save" data-index="${i===null?'':i}" type="button">Сохранить программу</button>${i!==null?`<button class="danger full" data-action="program-delete" data-index="${i}" type="button">Удалить программу</button>`:''}</section>${back('programs')}`}
 function certificates(){const a=read(K.certificates,[]);return `${head('ЛОЯЛЬНОСТЬ · СЕРТИФИКАТЫ','Сертификаты')}<div class="loyalty-list">${a.length?a.map((x,i)=>`<button class="loyalty-card" data-action="certificate-edit" data-index="${i}" type="button"><span><b>${esc(x.name)}</b><small>Номинал ${money(x.nominal)} · остаток ${money(x.balance)}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Сертификатов пока нет</div>'}</div><button class="primary full service-add" data-action="certificate-create" type="button">Создать сертификат</button>${back('certificates')}`}
 function certificateEditor(i=null){const a=read(K.certificates,[]),x=i===null?{name:'',nominal:5000,balance:5000,expires:''}:{...a[i]};return `${head('ЛОЯЛЬНОСТЬ · СЕРТИФИКАТ',i===null?'Новый сертификат':'Сертификат')}<section class="loyalty-form"><label class="service-field"><span>Название</span><input data-c="name" value="${esc(x.name)}"></label><label class="service-field"><span>Номинал</span><input data-c="nominal" type="number" min="1" value="${esc(x.nominal)}"></label><label class="service-field"><span>Действует до</span><input data-c="expires" type="date" value="${esc(x.expires)}"></label><button class="primary full" data-action="certificate-save" data-index="${i===null?'':i}" type="button">Сохранить</button></section>${back('certificates')}`}
 function subscriptions(){const a=read(K.subscriptions,[]);return `${head('ЛОЯЛЬНОСТЬ · АБОНЕМЕНТЫ','Абонементы')}<div class="loyalty-list">${a.length?a.map((x,i)=>`<button class="loyalty-card" data-action="subscription-edit" data-index="${i}" type="button"><span><b>${esc(x.name)}</b><small>${x.visits} посещений · ${money(x.price)}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Абонементов пока нет</div>'}</div><button class="primary full service-add" data-action="subscription-create" type="button">Создать абонемент</button>${back('subscriptions')}`}
 function subscriptionEditor(i=null){const a=read(K.subscriptions,[]),x=i===null?{name:'',visits:5,price:0,expires:''}:{...a[i]};return `${head('ЛОЯЛЬНОСТЬ · АБОНЕМЕНТ',i===null?'Новый абонемент':'Абонемент')}<section class="loyalty-form"><label class="service-field"><span>Название</span><input data-s="name" value="${esc(x.name)}"></label><label class="service-field"><span>Количество посещений</span><input data-s="visits" type="number" min="1" value="${esc(x.visits)}"></label><label class="service-field"><span>Цена</span><input data-s="price" type="number" min="0" value="${esc(x.price)}"></label><label class="service-field"><span>Действует до</span><input data-s="expires" type="date" value="${esc(x.expires)}"></label><button class="primary full" data-action="subscription-save" data-index="${i===null?'':i}" type="button">Сохранить</button></section>${back('subscriptions')}`}
 function referrals(){const x=read(K.referrals,{rewardType:'money',rewardValue:500});return `${head('ЛОЯЛЬНОСТЬ · РЕФЕРАЛЬНАЯ ПРОГРАММА','Реферальная программа')}<section class="loyalty-form"><label class="service-field"><span>Вознаграждение</span><select data-r="type"><option value="money" ${x.rewardType==='money'?'selected':''}>Деньги на личный счёт</option><option value="discount" ${x.rewardType==='discount'?'selected':''}>Скидка, %</option></select></label><label class="service-field"><span>Значение</span><input data-r="value" type="number" min="1" value="${esc(x.rewardValue)}"></label><button class="primary full" data-action="referral-save" type="button">Сохранить</button></section>${back('referrals')}`}
 function accounts(){const a=read(K.accounts,[]);return `${head('ЛОЯЛЬНОСТЬ · ЛИЧНЫЙ СЧЁТ','Личный счёт')}<div class="loyalty-list">${a.length?a.map((x,i)=>`<button class="loyalty-card" data-action="account-edit" data-index="${i}" type="button"><span><b>${esc(x.clientName||x.clientId)}</b><small>Баланс: ${money(x.balance)}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Личных счетов пока нет</div>'}</div><button class="primary full service-add" data-action="account-create" type="button">Создать личный счёт</button>${back('accounts')}`}
 function accountEditor(i=null){const a=read(K.accounts,[]),x=i===null?{clientId:'',balance:0,transactions:[]}:{...a[i]};return `${head('ЛОЯЛЬНОСТЬ · ЛИЧНЫЙ СЧЁТ',i===null?'Новый счёт':'Личный счёт')}<section class="loyalty-form"><label class="service-field"><span>Клиент</span><select data-a="client"><option value="">Выберите клиента</option>${clients().map(c=>{const id=c.client_id||c.id||'';return `<option value="${esc(id)}" ${String(id)===String(x.clientId)?'selected':''}>${esc(c.name||c.full_name||id)}</option>`}).join('')}</select></label><div class="balance-box"><span>Баланс</span><b>${money(x.balance)}</b></div><label class="service-field"><span>Сумма операции</span><input data-a="amount" type="number" min="1" placeholder="500"></label><div class="two-actions"><button class="secondary" data-action="account-op" data-operation="add" type="button">+ Начислить</button><button class="secondary" data-action="account-op" data-operation="spend" type="button">− Списать</button></div></section>${back('accounts')}`}
 function deposits(){const p=read(K.depositPrograms,[]),d=read(K.deposits,[]),today=new Date().toISOString().slice(0,10);return `${head('ЛОЯЛЬНОСТЬ · ДЕПОЗИТЫ','Депозиты')}<section class="section-title">Программы депозитов</section><div class="loyalty-list">${p.length?p.map((x,i)=>`<button class="loyalty-card" data-action="deposit-edit" data-index="${i}" type="button"><span><b>${esc(x.name)}</b><small>Взнос ${money(x.amount)} · скидка ${Number(x.discount||0)}% · ${esc(x.startDate)} — ${esc(x.endDate)}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Депозитных программ пока нет</div>'}</div><button class="primary full service-add" data-action="deposit-create" type="button">Создать депозит</button><section class="section-title">Подключённые депозиты</section><div class="loyalty-list">${d.length?d.map((x,i)=>{const expired=x.endDate&&x.endDate<today;return `<button class="loyalty-card" data-action="deposit-instance" data-index="${i}" type="button"><span><b>${esc(x.clientName||x.clientId||'Клиент')}</b><small>${esc(x.programName||'Депозит')} · остаток ${money(expired?0:x.balance)} · ${expired?'срок истёк':`до ${esc(x.endDate)}`}</small></span><span>›</span></button>`}).join(''):'<div class="loyalty-empty">Подключённых депозитов пока нет</div>'}</div><button class="primary full service-add" data-action="deposit-assign" type="button">Подключить депозит клиенту</button>${back('deposits')}`}
 function depositEditor(i=null){const a=read(K.depositPrograms,[]),x=i===null?{name:'',amount:'',discount:20,startDate:'',endDate:''}:{...a[i]};return `${head('ЛОЯЛЬНОСТЬ · ДЕПОЗИТ',i===null?'Новый депозит':'Изменить депозит')}<section class="loyalty-form"><label class="service-field"><span>Название</span><input data-d="name" value="${esc(x.name)}" placeholder="VIP 50"></label><label class="service-field"><span>Сумма депозита</span><input data-d="amount" type="number" min="1" value="${esc(x.amount)}" placeholder="50000"></label><label class="service-field"><span>Скидка</span><input data-d="discount" type="number" min="0" max="100" value="${esc(x.discount)}"></label><label class="service-field"><span>Дата начала</span><input data-d="startDate" type="date" value="${esc(x.startDate)}"></label><label class="service-field"><span>Дата завершения</span><input data-d="endDate" type="date" value="${esc(x.endDate)}"></label><button class="primary full" data-action="deposit-save" data-index="${i===null?'':i}" type="button">Сохранить депозит</button>${i!==null?`<button class="danger full" data-action="deposit-delete" data-index="${i}" type="button">Удалить депозит</button>`:''}</section>${back('deposits')}`}
 function depositAssign(){const p=read(K.depositPrograms,[]),cs=clients();return `${head('ЛОЯЛЬНОСТЬ · ДЕПОЗИТ','Подключить клиенту')}<section class="loyalty-form"><label class="service-field"><span>Программа</span><select data-di="program"><option value="">Выберите программу</option>${p.map((x,i)=>`<option value="${i}">${esc(x.name)} · ${money(x.amount)}</option>`).join('')}</select></label><label class="service-field"><span>Клиент</span><select data-di="client"><option value="">Выберите клиента</option>${cs.map(c=>{const id=c.client_id||c.id||'';return `<option value="${esc(id)}">${esc(c.name||c.full_name||id)}</option>`}).join('')}</select></label><button class="primary full" data-action="deposit-assign-save" type="button">Подключить</button></section>${back('deposits')}`}
 function depositInstance(i){const d=read(K.deposits,[]),x=d[i];if(!x)return deposits();const today=new Date().toISOString().slice(0,10),expired=x.endDate&&x.endDate<today;return `${head('ЛОЯЛЬНОСТЬ · ДЕПОЗИТ',esc(x.programName||'Депозит'))}<section class="loyalty-form"><div class="balance-box"><span>Баланс</span><b>${money(expired?0:x.balance)}</b></div><div class="info-box">Клиент: ${esc(x.clientName||x.clientId)}<br>Скидка: ${Number(x.discount||0)}%<br>Период: ${esc(x.startDate)} — ${esc(x.endDate)}${expired?'<br><b>Срок истёк: остаток сгорел.</b>':''}</div>${!expired?`<label class="service-field"><span>Списать</span><input data-di-spend type="number" min="1" max="${Number(x.balance||0)}" placeholder="500"></label><button class="primary full" data-action="deposit-spend" data-index="${i}" type="button">Списать с депозита</button>`:''}</section>${back('deposits')}`}
 function renderSection(s,i=null){if(s==='home')return home();if(s==='programs')return programs();if(s==='program-editor')return programEditor(i);if(s==='certificates')return certificates();if(s==='certificate-editor')return certificateEditor(i);if(s==='subscriptions')return subscriptions();if(s==='subscription-editor')return subscriptionEditor(i);if(s==='referrals')return referrals();if(s==='accounts')return accounts();if(s==='account-editor')return accountEditor(i);if(s==='deposits')return deposits();if(s==='deposit-editor')return depositEditor(i);if(s==='deposit-assign')return depositAssign();if(s==='deposit-instance')return depositInstance(i);return home()}
 let section='home',index=null;
 function go(s,i=null){section=s;index=i;window.render()}
 function val(s){return document.querySelector(s)?.value??''}
 function handle(a,e){
   const i=e.dataset.index===''?null:(e.dataset.index!==undefined?Number(e.dataset.index):null);
   if(a==='loyalty-back'){if(e.dataset.target==='settings')return navigate('settings');return go(e.dataset.target)}
   if(a==='loyalty-section')return go(e.dataset.section);
   if(a==='program-create')return go('program-editor');
   if(a==='program-edit')return go('program-editor',i);
   if(a==='program-delete'){const x=read(K.programs,[]);x.splice(i,1);write(K.programs,x);return go('programs')}
   if(a==='program-save'){const p={name:val('[data-p="name"]').trim(),condition:val('[data-p="condition"]'),threshold:Number(val('[data-p="threshold"]')),reward:val('[data-p="reward"]'),discount:Number(val('[data-p="discount"]')||0),money:Number(val('[data-p="money"]')||0),scope:val('[data-p="scope"]'),freeMode:document.querySelector('[data-p="freeMode"]:checked')?.value||'procedure',freeProcedureIndex:val('[data-p="freeProcedureIndex"]'),freeManual:val('[data-p="freeManual"]')};if(!p.name||p.threshold<1||(p.reward==='discount'&&(p.discount<0||p.discount>100))||(p.reward==='money'&&p.money<1)||(p.reward==='free'&&p.freeMode==='manual'&&!p.freeManual.trim()))return alert('Заполните обязательные поля программы.');const x=read(K.programs,[]);if(i===null)x.push(p);else x[i]=p;write(K.programs,x);return go('programs')}
   if(a==='certificate-create')return go('certificate-editor');
   if(a==='certificate-edit')return go('certificate-editor',i);
   if(a==='certificate-save'){const x={name:val('[data-c="name"]').trim(),nominal:Number(val('[data-c="nominal"]')),balance:Number(val('[data-c="nominal"]')),expires:val('[data-c="expires"]')};if(!x.name||x.nominal<1)return alert('Заполните название и номинал.');const a=read(K.certificates,[]);if(i===null)a.push(x);else a[i]=x;write(K.certificates,a);return go('certificates')}
   if(a==='subscription-create')return go('subscription-editor');
   if(a==='subscription-edit')return go('subscription-editor',i);
   if(a==='subscription-save'){const x={name:val('[data-s="name"]').trim(),visits:Number(val('[data-s="visits"]')),price:Number(val('[data-s="price"]')),expires:val('[data-s="expires"]')};if(!x.name||x.visits<1)return alert('Заполните название и количество посещений.');const a=read(K.subscriptions,[]);if(i===null)a.push(x);else a[i]=x;write(K.subscriptions,a);return go('subscriptions')}
   if(a==='referral-save'){write(K.referrals,{rewardType:val('[data-r="type"]'),rewardValue:Number(val('[data-r="value"]'))});return go('referrals')}
   if(a==='account-create')return go('account-editor');
   if(a==='account-edit')return go('account-editor',i);
   if(a==='account-op'){const x=read(K.accounts,[]);if(i===null||i===undefined)return alert('Сначала выберите счёт.');const amount=Number(val('[data-a="amount"]'));if(amount<=0)return alert('Введите сумму.');const item=x[i];if(!item)return alert('Счёт не найден.');if(e.dataset.operation==='spend'&&Number(item.balance)<amount)return alert('Недостаточный баланс.');item.balance=Number(item.balance||0)+(e.dataset.operation==='add'?amount:-amount);item.transactions=arr(item.transactions);item.transactions.push({type:e.dataset.operation,amount,date:new Date().toISOString()});write(K.accounts,x);return go('account-editor',i)}
   if(a==='deposit-create')return go('deposit-editor');
   if(a==='deposit-edit')return go('deposit-editor',i);
   if(a==='deposit-delete'){const x=read(K.depositPrograms,[]);x.splice(i,1);write(K.depositPrograms,x);return go('deposits')}
   if(a==='deposit-save'){const x={name:val('[data-d="name"]').trim(),amount:Number(val('[data-d="amount"]')),discount:Number(val('[data-d="discount"]')),startDate:val('[data-d="startDate"]'),endDate:val('[data-d="endDate"]')};if(!x.name||x.amount<=0||x.discount<0||x.discount>100||!x.startDate||!x.endDate||x.endDate<x.startDate)return alert('Заполните название, сумму, скидку и корректный период действия.');const d=read(K.depositPrograms,[]);if(i===null)d.push(x);else d[i]=x;write(K.depositPrograms,d);return go('deposits')}
   if(a==='deposit-assign')return go('deposit-assign');
   if(a==='deposit-assign-save'){const pi=Number(val('[data-di="program"]')),cid=val('[data-di="client"]'),p=read(K.depositPrograms,[])[pi];if(!p||!cid)return alert('Выберите программу и клиента.');const c=clients().find(x=>String(x.client_id||x.id||'')===String(cid)),d=read(K.deposits,[]);d.push({programId:pi,programName:p.name,clientId:cid,clientName:c?.name||c?.full_name||cid,initialAmount:Number(p.amount),balance:Number(p.amount),discount:Number(p.discount),startDate:p.startDate,endDate:p.endDate,createdAt:new Date().toISOString(),transactions:[]});write(K.deposits,d);return go('deposits')}
   if(a==='deposit-instance')return go('deposit-instance',i);
   if(a==='deposit-spend'){const d=read(K.deposits,[]),item=d[i],amount=Number(val('[data-di-spend]')),today=new Date().toISOString().slice(0,10);if(!item||item.endDate<today)return alert('Срок депозита истёк.');if(amount<=0||amount>Number(item.balance))return alert('Недостаточный баланс депозита.');item.balance=Number(item.balance)-amount;item.transactions=arr(item.transactions);item.transactions.push({type:'spend',amount,date:new Date().toISOString()});write(K.deposits,d);return go('deposit-instance',i)}
 }
 CoBook.modules.loyalty={render:()=>{const base=renderSection(section,index);return shell(base)},handle};
})();
