(function(){
 const MATERIALS_KEY='cobook_work_materials';
 const RECIPES_KEY='cobook_recipes';
 const categories={
  'Красители':['Гель-краситель','Крем-краситель','Аммиачный краситель','Безаммиачный краситель'],
  'Оксиды':['Оксид'],
  'Шампуни':['Шампунь'],
  'Инвентарь':['Инвентарь'],
  'Другое':['Другое']
 };
 const read=key=>readStorage(key,[]);
 const save=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
 let view='recipes', editor=false, draftSections=[];
 function materials(){return Array.isArray(read(MATERIALS_KEY))?read(MATERIALS_KEY):[]}
 function recipes(){return Array.isArray(read(RECIPES_KEY))?read(RECIPES_KEY):[]}
 function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
 function tab(){return `<div class="work-tabs"><button class="work-tab ${view==='recipes'?'active':''}" data-action="work-tab-recipes" type="button">Рецепты</button><button class="work-tab ${view==='materials'?'active':''}" data-action="work-tab-materials" type="button">Материалы</button></div>`}
 function render(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Рабочие материалы</h1><p>Материалы, из которых составляются рабочие рецепты.</p></section>${tab()}${view==='recipes'?renderRecipes():renderMaterials()}<div class="section-back-wrap"><button class="section-back-button" data-action="navigate" data-page="settings" type="button">Назад</button></div>`)}
 function renderRecipes(){const list=recipes(); if(editor)return renderEditor(); return `<div class="work-toolbar"><b>Сохранённые рецепты</b><button class="primary work-add" data-action="recipe-new" type="button">Добавить рецепт</button></div>${list.length?`<div class="work-list">${list.map(r=>`<button class="work-card" data-action="recipe-open" data-id="${esc(r.id)}" type="button"><span><b>${esc(r.name)}</b><small>${r.sections.length} ${r.sections.length===1?'состав':'состава'}</small></span><span>›</span></button>`).join('')}</div>`:`<div class="work-empty"><b>Рецептов пока нет</b><span>Создайте первый рецепт и добавьте в него один или несколько составов.</span></div>`}`}
 function renderMaterials(){const list=materials(); return `<div class="work-toolbar"><b>Справочник материалов</b><button class="primary work-add" data-action="material-new" type="button">Добавить материал</button></div>${list.length?`<div class="work-list">${list.map(m=>`<div class="work-card static"><span><b>${esc(m.name)}</b><small>${esc(m.category)}${m.type&&m.type!=='Другое'?' · '+esc(m.type):''}</small></span><button class="work-delete" data-action="material-delete" data-id="${esc(m.id)}" type="button">×</button></div>`).join('')}</div>`:`<div class="work-empty"><b>Материалов пока нет</b><span>Добавьте краски, оксиды, шампуни, инвентарь и другие рабочие материалы.</span></div>`}`}
 function materialForm(){return `<div class="work-overlay"><div class="work-sheet"><div class="work-sheet-head"><b>Новый материал</b><button class="work-close" data-action="work-close" type="button">×</button></div><form data-material-form><label class="work-field"><span>Название материала</span><input name="name" required placeholder="Например, 5.0"></label><label class="work-field"><span>Категория</span><select name="category" data-material-category required>${Object.keys(categories).map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label class="work-field"><span>Тип / метка</span><select name="type" data-material-type>${categories['Красители'].map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select></label><button class="primary" type="submit">Сохранить</button></form></div></div>`}
 function renderEditor(){return `<div class="work-editor"><div class="work-editor-title"><b>Новый рецепт</b></div><form data-recipe-form><label class="work-field"><span>Название рецепта</span><input name="name" required placeholder="Например, Холодный шатен"></label><div class="composition-head"><b>Составы</b><button class="secondary work-small" data-action="recipe-add-section" type="button">+ Состав</button></div>${draftSections.map((s,i)=>renderSection(s,i)).join('')}<button class="primary" type="submit">Сохранить рецепт</button><button class="section-back-button" data-action="recipe-cancel" type="button">Отмена</button></form></div>`}
 function renderSection(s,i){return `<div class="composition"><div class="composition-title"><input class="section-name" data-section-name="${i}" value="${esc(s.name)}" aria-label="Название состава" placeholder="Корни"><button class="work-delete" data-action="recipe-remove-section" data-index="${i}" type="button">×</button></div>${s.items.map((it,j)=>renderItem(it,i,j)).join('')}<button class="secondary work-small" data-action="recipe-add-item" data-index="${i}" type="button">+ Материал</button></div>`}
 function renderItem(it,i,j){const list=materials();const cats=Object.keys(categories);const types=categories[it.category]||[];const filtered=list.filter(m=>m.category===it.category&&(!it.type||it.type==='Другое'||m.type===it.type));return `<div class="recipe-item"><select data-item-category="${i}:${j}">${cats.map(c=>`<option value="${esc(c)}" ${it.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select data-item-type="${i}:${j}"><option value="">Любой тип</option>${types.map(t=>`<option value="${esc(t)}" ${it.type===t?'selected':''}>${esc(t)}</option>`).join('')}</select><select data-item-material="${i}:${j}" ${filtered.length?'':'disabled'}><option value="">${filtered.length?'Выберите материал':'Сначала добавьте материал'}</option>${filtered.map(m=>`<option value="${esc(m.id)}" ${it.materialId===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select><input data-item-qty="${i}:${j}" value="${esc(it.quantity)}" placeholder="Количество"><button class="work-delete" data-action="recipe-remove-item" data-index="${i}" data-item="${j}" type="button">×</button></div>`}
 function showMaterialForm(){document.body.insertAdjacentHTML('beforeend',materialForm())}
 function syncDraft(){document.querySelectorAll('[data-section-name]').forEach(el=>{const i=+el.dataset.sectionName;if(draftSections[i])draftSections[i].name=el.value});document.querySelectorAll('[data-item-category]').forEach(el=>{const [i,j]=el.dataset.itemCategory.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].category=el.value});document.querySelectorAll('[data-item-type]').forEach(el=>{const [i,j]=el.dataset.itemType.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].type=el.value});document.querySelectorAll('[data-item-material]').forEach(el=>{const [i,j]=el.dataset.itemMaterial.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].materialId=el.value});document.querySelectorAll('[data-item-qty]').forEach(el=>{const [i,j]=el.dataset.itemQty.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].quantity=el.value})}
 function handle(action,e){
  if(action==='work-tab-recipes'){view='recipes';editor=false;return render()}
  if(action==='work-tab-materials'){view='materials';editor=false;return render()}
  if(action==='material-new')return showMaterialForm();
  if(action==='work-close'){e.closest('.work-overlay')?.remove();return}
  if(action==='material-delete'){const next=materials().filter(m=>m.id!==e.dataset.id);save(MATERIALS_KEY,next);return render()}
  if(action==='recipe-new'){draftSections=[{name:'Корни',items:[{category:'Красители',type:'',materialId:'',quantity:''}]}];editor=true;return render()}
  if(action==='recipe-add-section'){syncDraft();draftSections.push({name:'Новый состав',items:[{category:'Красители',type:'',materialId:'',quantity:''}]});return render()}
  if(action==='recipe-remove-section'){syncDraft();if(draftSections.length>1)draftSections.splice(+e.dataset.index,1);return render()}
  if(action==='recipe-add-item'){syncDraft();draftSections[+e.dataset.index].items.push({category:'Красители',type:'',materialId:'',quantity:''});return render()}
  if(action==='recipe-remove-item'){syncDraft();draftSections[+e.dataset.index].items.splice(+e.dataset.item,1);return render()}
  if(action==='recipe-cancel'){editor=false;return render()}
 }
 document.addEventListener('submit',e=>{const mf=e.target.closest('[data-material-form]');if(mf){e.preventDefault();const d=Object.fromEntries(new FormData(mf).entries());const arr=materials();arr.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:d.name.trim(),category:d.category,type:d.type});save(MATERIALS_KEY,arr);mf.closest('.work-overlay')?.remove();view='materials';return render()}const rf=e.target.closest('[data-recipe-form]');if(rf){e.preventDefault();syncDraft();const data=new FormData(rf);const arr=recipes();arr.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:String(data.get('name')).trim(),sections:draftSections.map(s=>({name:s.name.trim()||'Состав',items:s.items.filter(it=>it.materialId||it.quantity)}))});save(RECIPES_KEY,arr);editor=false;view='recipes';return render()}});
 document.addEventListener('change',e=>{if(!editor)return;const c=e.target.dataset.itemCategory;if(c){const [i,j]=c.split(':').map(Number);draftSections[i].category=e.target.value;draftSections[i].type='';draftSections[i].materialId='';return render()}const t=e.target.dataset.itemType;if(t){const [i,j]=t.split(':').map(Number);draftSections[i].type=e.target.value;draftSections[i].items[j].materialId='';return render()}}
 CoBook.modules.work={render,handle};
})();
