(function(){
 const MATERIALS_KEY='cobook_work_materials',RECIPES_KEY='cobook_recipes';
 const categories={'Красители':['Гель-краситель','Крем-краситель','Аммиачный краситель','Безаммиачный краситель'],'Оксиды':['Оксид'],'Шампуни':['Шампунь'],'Инвентарь':['Инвентарь'],'Другое':['Другое']};
 const read=key=>readStorage(key,[]),save=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
 let view='recipes',editor=false,draftSections=[],selectedRecipe=null;
 const materials=()=>{const v=read(MATERIALS_KEY,[]);return Array.isArray(v)?v:[]};
 const recipes=()=>{const v=read(RECIPES_KEY,[]);return Array.isArray(v)?v:[]};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const newId=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
 function render(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Рабочие материалы</h1><p>Материалы, из которых составляются рабочие рецепты.</p></section><div class="service-tabs" role="tablist"><button class="service-tab ${view==='recipes'?'active':''}" data-action="materials-tab-recipes" type="button" role="tab" aria-selected="${view==='recipes'}">Рецепты</button><button class="service-tab ${view==='materials'?'active':''}" data-action="materials-tab-list" type="button" role="tab" aria-selected="${view==='materials'}">Материалы</button></div>${view==='recipes'?(selectedRecipe?renderRecipeDetail():renderRecipes()):renderMaterials()}<div class="section-back-wrap"><button class="section-back-button" data-action="navigate" data-page="settings" type="button">Назад</button></div>`)}
 function renderRecipes(){if(editor)return renderEditor();const list=recipes();return `<div class="work-toolbar"><b>Сохранённые рецепты</b></div>${list.length?`<div class="work-list">${list.map(r=>`<button class="work-card" data-action="materials-recipe-open" data-id="${esc(r.id)}" type="button"><span><b>${esc(r.name)}</b><small>${r.sections.length} ${r.sections.length===1?'состав':'состава'}</small></span><span>›</span></button>`).join('')}</div>`:`<div class="work-empty"><b>Рецептов пока нет</b><span>Создайте первый рецепт и добавьте в него один или несколько составов.</span></div>`}<button class="primary work-add full" data-action="materials-recipe-new" type="button">Добавить рецепт</button>`}
 function renderRecipeDetail(){const r=selectedRecipe;if(!r)return renderRecipes();return `<div class="work-editor"><div class="work-editor-title"><b>${esc(r.name)}</b></div>${r.sections.map(s=>`<div class="composition"><div class="composition-title"><b>${esc(s.name)}</b></div>${s.items.length?s.items.map(it=>{const m=materials().find(x=>x.id===it.materialId);return `<div class="recipe-detail-row"><span>${esc(m?m.name:'Материал не найден')}</span><small>${esc(it.quantity||'')}</small></div>`}).join(''):`<div class="work-empty">Состав пуст</div>`}</div>`).join('')}<button class="section-back-button" data-action="materials-recipe-detail-close" type="button">Назад к рецептам</button></div>`}
 function renderMaterials(){const list=materials();return `<div class="work-toolbar"><b>Справочник материалов</b></div>${list.length?`<div class="work-list">${list.map(m=>`<div class="work-card static"><span><b>${esc(m.name)}</b><small>${esc(m.category)}${m.type?' · '+esc(m.type):''}</small></span><button class="work-delete" data-action="materials-delete" data-id="${esc(m.id)}" type="button">×</button></div>`).join('')}</div>`:`<div class="work-empty"><b>Материалов пока нет</b><span>Добавьте краски, оксиды, шампуни, инвентарь и другие рабочие материалы.</span></div>`}<button class="primary work-add full" data-action="materials-new" type="button">Добавить материал</button>`}
 function materialTypes(category){return categories[category]||['Другое']}
 function materialForm(){return `<div class="work-overlay"><div class="work-sheet"><div class="work-sheet-head"><b>Новый материал</b><button class="work-close" data-action="materials-close" type="button">×</button></div><form data-material-form><label class="work-field"><span>Название материала</span><input name="name" required placeholder="Например, 5.0"></label><label class="work-field"><span>Категория / метка</span><select name="category" data-material-category required>${Object.keys(categories).map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('')}</select></label><label class="work-field"><span>Тип / метка</span><select name="type" data-material-type>${materialTypes('Красители').map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}</select></label><button class="primary" type="submit">Сохранить</button></form></div></div>`}
 function renderEditor(){return `<div class="work-editor"><div class="work-editor-title"><b>Новый рецепт</b></div><form data-recipe-form><label class="work-field"><span>Название рецепта</span><input name="name" required placeholder="Например, Холодный шатен"></label><div class="composition-head"><b>Составы</b><button class="secondary work-small" data-action="materials-recipe-add-section" type="button">+ Состав</button></div>${draftSections.map((s,i)=>renderSection(s,i)).join('')}<button class="primary" type="submit">Сохранить рецепт</button><button class="section-back-button" data-action="materials-recipe-cancel" type="button">Отмена</button></form></div>`}
 function renderSection(s,i){return `<div class="composition"><div class="composition-title"><input class="section-name" data-section-name="${i}" value="${esc(s.name)}" placeholder="Корни"><button class="work-delete" data-action="materials-recipe-remove-section" data-index="${i}" type="button">×</button></div>${s.items.map((it,j)=>renderItem(it,i,j)).join('')}<button class="secondary work-small" data-action="materials-recipe-add-item" data-index="${i}" type="button">+ Материал</button></div>`}
 function renderItem(it,i,j){const list=materials(),cats=Object.keys(categories),types=categories[it.category]||[],filtered=list.filter(m=>m.category===it.category&&(!it.type||m.type===it.type));return `<div class="recipe-item"><select data-item-category="${i}:${j}">${cats.map(c=>`<option value="${esc(c)}" ${it.category===c?'selected':''}>${esc(c)}</option>`).join('')}</select><select data-item-type="${i}:${j}"><option value="">Любой тип</option>${types.map(t=>`<option value="${esc(t)}" ${it.type===t?'selected':''}>${esc(t)}</option>`).join('')}</select><select data-item-material="${i}:${j}" ${filtered.length?'':'disabled'}><option value="">${filtered.length?'Выберите материал':'Сначала добавьте материал'}</option>${filtered.map(m=>`<option value="${esc(m.id)}" ${it.materialId===m.id?'selected':''}>${esc(m.name)}</option>`).join('')}</select><input data-item-qty="${i}:${j}" value="${esc(it.quantity)}" placeholder="Количество"><button class="work-delete" data-action="materials-recipe-remove-item" data-index="${i}" data-item="${j}" type="button">×</button></div>`}
 function showMaterialForm(){document.body.insertAdjacentHTML('beforeend',materialForm())}
 function syncDraft(){document.querySelectorAll('[data-section-name]').forEach(el=>{const i=+el.dataset.sectionName;if(draftSections[i])draftSections[i].name=el.value});document.querySelectorAll('[data-item-category]').forEach(el=>{const [i,j]=el.dataset.itemCategory.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].category=el.value});document.querySelectorAll('[data-item-type]').forEach(el=>{const [i,j]=el.dataset.itemType.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].type=el.value});document.querySelectorAll('[data-item-material]').forEach(el=>{const [i,j]=el.dataset.itemMaterial.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].materialId=el.value});document.querySelectorAll('[data-item-qty]').forEach(el=>{const [i,j]=el.dataset.itemQty.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].quantity=el.value})}
 function rerender(){app.innerHTML=render()}
 function handle(action,e){
  if(action==='materials-tab-recipes'){view='recipes';editor=false;selectedRecipe=null;rerender();return}
  if(action==='materials-tab-list'){view='materials';editor=false;selectedRecipe=null;rerender();return}
  if(action==='materials-new')return showMaterialForm();
  if(action==='materials-close'){e.closest('.work-overlay')?.remove();return}
  if(action==='materials-delete'){save(MATERIALS_KEY,materials().filter(m=>m.id!==e.dataset.id));rerender();return}
  if(action==='materials-recipe-new'){draftSections=[{name:'Корни',items:[{category:'Красители',type:'',materialId:'',quantity:''}]}];editor=true;selectedRecipe=null;rerender();return}
  if(action==='materials-recipe-open'){selectedRecipe=recipes().find(r=>r.id===e.dataset.id)||null;rerender();return}
  if(action==='materials-recipe-detail-close'){selectedRecipe=null;rerender();return}
  if(action==='materials-recipe-add-section'){syncDraft();draftSections.push({name:'Новый состав',items:[{category:'Красители',type:'',materialId:'',quantity:''}]});rerender();return}
  if(action==='materials-recipe-remove-section'){syncDraft();if(draftSections.length>1)draftSections.splice(+e.dataset.index,1);rerender();return}
  if(action==='materials-recipe-add-item'){syncDraft();draftSections[+e.dataset.index].items.push({category:'Красители',type:'',materialId:'',quantity:''});rerender();return}
  if(action==='materials-recipe-remove-item'){syncDraft();draftSections[+e.dataset.index].items.splice(+e.dataset.item,1);rerender();return}
  if(action==='materials-recipe-cancel'){editor=false;rerender();return}
 }
 document.addEventListener('submit',e=>{const mf=e.target.closest('[data-material-form]');if(mf){e.preventDefault();const d=Object.fromEntries(new FormData(mf).entries()),arr=materials();arr.push({id:newId(),name:d.name.trim(),category:d.category,type:d.type});save(MATERIALS_KEY,arr);mf.closest('.work-overlay')?.remove();view='materials';app.innerHTML=render();return}const rf=e.target.closest('[data-recipe-form]');if(rf){e.preventDefault();syncDraft();const data=new FormData(rf),arr=recipes();arr.push({id:newId(),name:String(data.get('name')).trim(),sections:draftSections.map(s=>({name:s.name.trim()||'Состав',items:s.items.filter(it=>it.materialId||it.quantity)}))});save(RECIPES_KEY,arr);editor=false;view='recipes';app.innerHTML=render();return}});
 document.addEventListener('change',e=>{if(!editor)return;const cat=e.target.dataset.itemCategory;if(cat){const [i,j]=cat.split(':').map(Number);draftSections[i].items[j].category=e.target.value;draftSections[i].items[j].type='';draftSections[i].items[j].materialId='';app.innerHTML=render();return}const typ=e.target.dataset.itemType;if(typ){const [i,j]=typ.split(':').map(Number);draftSections[i].items[j].type=e.target.value;draftSections[i].items[j].materialId='';app.innerHTML=render();return}const mc=e.target.dataset.materialCategory;if(mc){const form=e.target.closest('[data-material-form]'),type=form?.querySelector('[data-material-type]');if(type)type.innerHTML=materialTypes(e.target.value).map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}});
 CoBook.modules.work={render,handle};
})();
