(function(){
 const MATERIALS_KEY='cobook_work_materials',RECIPES_KEY='cobook_recipes';
 const categories={'Красители':['Гель-краситель','Крем-краситель','Аммиачный краситель','Безаммиачный краситель'],'Оксиды':['Оксид'],'Шампуни':['Шампунь'],'Инвентарь':['Инвентарь'],'Другое':['Другое']};
 const read=key=>readStorage(key,[]),save=(key,v)=>localStorage.setItem(key,JSON.stringify(v));
 let view='recipes',editor=false,draftSections=[],selectedRecipe=null;
 const materials=()=>{const v=read(MATERIALS_KEY,[]);return Array.isArray(v)?v:[]};
 const recipes=()=>{const v=read(RECIPES_KEY,[]);return Array.isArray(v)?v:[]};
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const newId=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
 const primary=(label,action,attrs='',className='')=>CoBook.ui.button({label,action,variant:'primary',attrs,className});
 const secondary=(label,action,attrs='',className='')=>CoBook.ui.button({label,action,variant:'secondary',attrs,className});
 const tab=(label,action,mode,active)=>CoBook.ui.button({label,action,variant:'secondary',attrs:`data-mode="${mode}" role="tab" aria-selected="${active}"`,className:`service-tab ${active?'active':''}`});
 function render(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Рабочие материалы</h1><p>Материалы, из которых составляются рабочие рецепты.</p></section><div class="service-tabs" role="tablist">${tab('Рецепты','materials-tab-recipes','recipes',view==='recipes')}${tab('Материалы','materials-tab-list','materials',view==='materials')}</div>${view==='recipes'?(selectedRecipe?renderRecipeDetail():renderRecipes()):renderMaterials()}<div class="section-back-wrap">${CoBook.ui.button({label:'Назад',action:'navigate',variant:'secondary',attrs:'data-page="settings"',className:'section-back-button'})}</div>`)}
 function renderRecipes(){if(editor)return renderEditor();const list=recipes();return `<div class="work-toolbar"><b>Сохранённые рецепты</b></div>${list.length?`<div class="ui-list work-list">${list.map(r=>CoBook.ui.listItem({title:r.name,subtitle:`${r.sections.length} ${r.sections.length===1?'состав':'состава'}`,rootTag:'button',rootAction:'materials-recipe-open',rootAttrs:`data-id="${esc(r.id)}"`,itemClass:'work-card'})).join('')}</div>`:`<div class="work-empty"><b>Рецептов пока нет</b><span>Создайте первый рецепт и добавьте в него один или несколько составов.</span></div>`}${primary('Добавить рецепт','materials-recipe-new','', 'work-add full')}`}
 function renderRecipeDetail(){const r=selectedRecipe;if(!r)return renderRecipes();return `<div class="work-editor"><div class="work-editor-title"><b>${esc(r.name)}</b></div>${r.sections.map(s=>`<div class="composition"><div class="composition-title"><b>${esc(s.name)}</b></div>${s.items.length?s.items.map(it=>{const m=materials().find(x=>x.id===it.materialId);return `<div class="recipe-detail-row"><span>${esc(m?m.name:'Материал не найден')}</span><small>${esc(it.quantity||'')}</small></div>`}).join(''):`<div class="work-empty">Состав пуст</div>`}</div>`).join('')}${CoBook.ui.button({label:'Назад к рецептам',action:'materials-recipe-detail-close',variant:'secondary',className:'section-back-button'})}</div>`}
 function renderMaterials(){const list=materials();return `<div class="work-toolbar"><b>Справочник материалов</b></div>${list.length?`<div class="ui-list work-list">${list.map(m=>CoBook.ui.listItem({title:m.name,subtitle:`${m.category}${m.type?' · '+m.type:''}`,action:'materials-delete',actionLabel:'×',actionClass:'danger',actionAttrs:`data-id="${esc(m.id)}"`,itemClass:'work-card'})).join('')}</div>`:`<div class="work-empty"><b>Материалов пока нет</b><span>Добавьте краски, оксиды, шампуни, инвентарь и другие рабочие материалы.</span></div>`}${primary('Добавить материал','materials-new','', 'work-add full')}`}
 function materialTypes(category){return categories[category]||['Другое']}
 function materialForm(){return CoBook.ui.bottomSheet({kind:'work-material',outerClassName:'work-overlay',className:'work-sheet',content:`<div class="work-sheet-head"><b>Новый материал</b>${CoBook.ui.button({label:'×',action:'materials-close',variant:'secondary',className:'work-close'})}</div><form data-material-form>${CoBook.ui.field({label:'Название материала',name:'name',placeholder:'Например, 5.0',attrs:'required'})}${CoBook.ui.select({label:'Категория / метка',name:'category',options:Object.keys(categories).map(c=>({value:c,label:c})),attrs:'required data-material-category'})}${CoBook.ui.select({label:'Тип / метка',name:'type',options:materialTypes('Красители').map(t=>({value:t,label:t})),attrs:'data-material-type'})}${primary('Сохранить','materials-save')}</form>`})}
 function renderEditor(){return `<div class="work-editor"><div class="work-editor-title"><b>Новый рецепт</b></div><form data-recipe-form>${CoBook.ui.field({label:'Название рецепта',name:'name',placeholder:'Например, Холодный шатен',attrs:'required'})}<div class="composition-head"><b>Составы</b>${secondary('+ Состав','materials-recipe-add-section','', 'work-small')}</div>${draftSections.map((s,i)=>renderSection(s,i)).join('')}${primary('Сохранить рецепт','recipe-save')}${CoBook.ui.button({label:'Отмена',action:'materials-recipe-cancel',variant:'secondary',className:'section-back-button'})}</form></div>`}
 function renderSection(s,i){return `<div class="composition"><div class="composition-title">${CoBook.ui.field({name:`section-name-${i}`,value:s.name,placeholder:'Корни',attrs:`data-section-name="${i}"`,bare:true})}${CoBook.ui.button({label:'×',action:'materials-recipe-remove-section',variant:'danger',attrs:`data-index="${i}"`,className:'work-delete'})}</div>${s.items.map((it,j)=>renderItem(it,i,j)).join('')}${secondary('+ Материал','materials-recipe-add-item',`data-index="${i}"`, 'work-small')}</div>`}
 function renderItem(it,i,j){const list=materials(),cats=Object.keys(categories),types=categories[it.category]||[],filtered=list.filter(m=>m.category===it.category&&(!it.type||m.type===it.type));return `<div class="recipe-item">${CoBook.ui.select({name:`item-category-${i}-${j}`,value:it.category,options:cats.map(c=>({value:c,label:c})),attrs:`data-item-category="${i}:${j}"`,bare:true})}${CoBook.ui.select({name:`item-type-${i}-${j}`,value:it.type,options:[{value:'',label:'Любой тип'},...types.map(t=>({value:t,label:t}))],attrs:`data-item-type="${i}:${j}"`,bare:true})}${CoBook.ui.select({name:`item-material-${i}-${j}`,value:it.materialId,options:[{value:'',label:filtered.length?'Выберите материал':'Сначала добавьте материал'},...filtered.map(m=>({value:m.id,label:m.name}))],attrs:`data-item-material="${i}:${j}" ${filtered.length?'':'disabled'}`,bare:true})}${CoBook.ui.field({name:`item-qty-${i}-${j}`,value:it.quantity,placeholder:'Количество',attrs:`data-item-qty="${i}:${j}"`,bare:true})}${CoBook.ui.button({label:'×',action:'materials-recipe-remove-item',variant:'danger',attrs:`data-index="${i}" data-item="${j}"`,className:'work-delete'})}</div>`}
 function showMaterialForm(){CoBook.ui.mountOverlay(materialForm())}
 function syncDraft(){document.querySelectorAll('[data-section-name]').forEach(el=>{const i=+el.dataset.sectionName;if(draftSections[i])draftSections[i].name=el.value});document.querySelectorAll('[data-item-category]').forEach(el=>{const [i,j]=el.dataset.itemCategory.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].category=el.value});document.querySelectorAll('[data-item-type]').forEach(el=>{const [i,j]=el.dataset.itemType.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].type=el.value});document.querySelectorAll('[data-item-material]').forEach(el=>{const [i,j]=el.dataset.itemMaterial.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].materialId=el.value});document.querySelectorAll('[data-item-qty]').forEach(el=>{const [i,j]=el.dataset.itemQty.split(':').map(Number);if(draftSections[i]?.items[j])draftSections[i].items[j].quantity=el.value})}
 function rerender(){window.render()}
 function handle(action,e){if(action==='materials-tab-recipes'){view='recipes';editor=false;selectedRecipe=null;rerender();return}if(action==='materials-tab-list'){view='materials';editor=false;selectedRecipe=null;rerender();return}if(action==='materials-new')return showMaterialForm();if(action==='materials-close'){e.closest('[data-modal]')?.remove();return}if(action==='materials-delete'){save(MATERIALS_KEY,materials().filter(m=>m.id!==e.dataset.id));rerender();return}if(action==='materials-save'){const form=e.closest('[data-material-form]');if(!form)return;const d=Object.fromEntries(new FormData(form).entries()),arr=materials();if(!String(d.name||'').trim())return;arr.push({id:newId(),name:String(d.name).trim(),category:d.category,type:d.type});save(MATERIALS_KEY,arr);form.closest('[data-modal]')?.remove();view='materials';rerender();return}if(action==='materials-recipe-new'){draftSections=[{name:'Корни',items:[{category:'Красители',type:'',materialId:'',quantity:''}]}];editor=true;selectedRecipe=null;rerender();return}if(action==='materials-recipe-open'){selectedRecipe=recipes().find(r=>r.id===e.dataset.id)||null;rerender();return}if(action==='materials-recipe-detail-close'){selectedRecipe=null;rerender();return}if(action==='materials-recipe-add-section'){syncDraft();draftSections.push({name:'Новый состав',items:[{category:'Красители',type:'',materialId:'',quantity:''}]});rerender();return}if(action==='materials-recipe-remove-section'){syncDraft();if(draftSections.length>1)draftSections.splice(+e.dataset.index,1);rerender();return}if(action==='materials-recipe-add-item'){syncDraft();draftSections[+e.dataset.index].items.push({category:'Красители',type:'',materialId:'',quantity:''});rerender();return}if(action==='materials-recipe-remove-item'){syncDraft();draftSections[+e.dataset.index].items.splice(+e.dataset.item,1);rerender();return}if(action==='materials-recipe-cancel'){editor=false;rerender();return}if(action==='recipe-save'){const form=e.closest('[data-recipe-form]');if(!form)return;syncDraft();const data=new FormData(form),name=String(data.get('name')||'').trim();if(!name)return;const arr=recipes();arr.push({id:newId(),name,sections:draftSections.map(s=>({name:s.name.trim()||'Состав',items:s.items.filter(it=>it.materialId||it.quantity)}))});save(RECIPES_KEY,arr);editor=false;view='recipes';rerender();return}}
 function handleChange(target){if(!editor)return;const cat=target.dataset.itemCategory;if(cat){const [i,j]=cat.split(':').map(Number);if(draftSections[i]?.items[j]){draftSections[i].items[j].category=target.value;draftSections[i].items[j].type='';draftSections[i].items[j].materialId='';window.render()}return}const typ=target.dataset.itemType;if(typ){const [i,j]=typ.split(':').map(Number);if(draftSections[i]?.items[j]){draftSections[i].items[j].type=target.value;draftSections[i].items[j].materialId='';window.render()}return}const mc=target.dataset.materialCategory;if(mc){const form=target.closest('[data-material-form]'),type=form?.querySelector('[data-material-type]');if(type)type.innerHTML=materialTypes(target.value).map(t=>`<option value="${esc(t)}">${esc(t)}</option>`).join('')}}
 CoBook.modules.work={render,handle,handleChange};
})();