const STORAGE_KEY='cobook-demo-v1';
const seed={master:{name:'Александр',specialty:'Парикмахер',bookingNotice:120,bookingHorizon:60,slotStep:30,cancelBefore:180},services:[{id:'s1',name:'Мужская стрижка',duration:60,price:3000,active:true},{id:'s2',name:'Стрижка + борода',duration:90,price:4000,active:true},{id:'s3',name:'Женская стрижка',duration:90,price:4500,active:true},{id:'s4',name:'Окрашивание',duration:180,price:9000,active:true},{id:'s5',name:'Укладка',duration:60,price:2500,active:true}],hours:{1:['10:00','20:00'],2:['10:00','20:00'],3:null,4:['10:00','20:00'],5:['10:00','20:00'],6:['10:00','18:00'],0:null},breaks:[{id:'b1',day:1,start:'14:00',end:'15:00'},{id:'b2',day:2,start:'14:00',end:'15:00'},{id:'b3',day:4,start:'14:00',end:'15:00'},{id:'b4',day:5,start:'14:00',end:'15:00'}],exceptions:{},bookings:[{id:'demo1',personId:'demo-person-001',personName:'Иван',serviceId:'s1',date:addDays(0),'start':'12:00','end':'13:00',price:3000,duration:60,status:'confirmed'},{id:'demo2',personId:'demo-person-002',personName:'Мария',serviceId:'s3',date:addDays(1),'start':'16:00','end':'17:30',price:4500,duration:90,status:'confirmed'}],person:{id:'demo-person-001',name:'Иван',phone:'+7 900 000-00-00'}};
function addDays(n){const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return iso(d)}
function iso(d){return d.toISOString().slice(0,10)}
function load(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY))||structuredClone(seed)}catch{return structuredClone(seed)}}
let db=load();let state={screen:'home',mode:'master',service:null,date:addDays(0),slot:null};
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(db))}
function esc(v){return String(v).replace(/[&<>'"]/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[x]))}
function money(v){return new Intl.NumberFormat('ru-RU').format(v)+' ₽'}
function fmtDate(s){return new Date(s+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}
function dow(s){return new Date(s+'T12:00:00').getDay()}
function mins(t){const [h,m]=t.split(':').map(Number);return h*60+m}
function hm(n){return String(Math.floor(n/60)).padStart(2,'0')+':'+String(n%60).padStart(2,'0')}
function service(id){return db.services.find(x=>x.id===id)}
function breaksFor(date){return db.breaks.filter(b=>b.day===dow(date))}
function overlaps(a,b,c,d){return a<c?c<b:b<d}
function isBlocked(date,start,end){if(db.exceptions[date]?.type==='dayoff')return true;for(const b of breaksFor(date)){if(overlaps(start,end,mins(b.start),mins(b.end)))return true}for(const x of db.bookings.filter(x=>x.date===date&&x.status!=='cancelled')){if(overlaps(start,end,mins(x.start),mins(x.end)))return true}return false}
function slots(date,s){const h=db.exceptions[date]?.type==='hours'?db.exceptions[date].hours:db.hours[dow(date)];if(!h)return [];const out=[];const duration=s.duration;for(let t=mins(h[0]);t+duration<=mins(h[1]);t+=db.master.slotStep){if(!isBlocked(date,t,t+duration))out.push(hm(t))}return out}
function render(){const app=document.getElementById('app');app.innerHTML=`<div class="shell"><header class="topbar"><div class="brand">CoBook</div><div class="subtitle">Онлайн-запись</div></header><main class="content">${state.mode==='master'?renderMaster():renderClient()}</main>${renderBottom()}</div>`;bind()}
function renderBottom(){return `<nav class="bottom"><div class="bottom-inner"><button class="nav ${state.screen==='home'?'active':''}" data-screen="home"><span class="nav-icon">⌂</span>Обзор</button><button class="nav ${state.screen==='calendar'?'active':''}" data-screen="calendar"><span class="nav-icon">▦</span>Календарь</button><button class="nav ${state.mode==='master'?'active':''}" data-toggle-mode="1"><span class="nav-icon">${state.mode==='master'?'⚙':'✂'}</span>${state.mode==='master'?'Мастер':'Запись'}</button></div></nav>`}
function renderMaster(){if(state.screen==='calendar')return calendar();if(state.screen==='services')return services();if(state.screen==='schedule')return schedule();return masterHome()}
function masterHome(){const active=db.services.filter(s=>s.active).length;const upcoming=db.bookings.filter(b=>b.status!=='cancelled').sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start)).slice(0,3);return `<div class="hero"><h1>Ваша запись готова</h1><p>${esc(db.master.name)} · ${esc(db.master.specialty)}</p></div><div class="tabs"><button class="tab active">Мастер</button><button class="tab" data-mode-client="1">Посмотреть глазами клиента</button></div><div class="card"><div class="row"><div><b>Настройка онлайн-записи</b><div class="small muted">Всё можно менять без кода</div></div><span class="badge green">Готово</span></div><div class="section-title">Сейчас настроено</div><div class="two"><div class="notice"><b>${active}</b><br>активных услуг</div><div class="notice"><b>${Object.values(db.hours).filter(Boolean).length}</b><br>рабочих дней</div></div></div><div class="card"><div class="row"><b>Ближайшие записи</b><button class="secondary" data-screen="calendar">Все</button></div>${upcoming.length?upcoming.map(bookingLine).join(''):'<div class="empty">Записей пока нет</div>'}</div><div class="section-title">Настройки</div><div class="card"><button class="service" data-screen="services"><div class="row"><b>Услуги и прайс</b><span>›</span></div><div class="small muted">Цена и длительность каждой услуги</div></button><button class="service" data-screen="schedule"><div class="row"><b>Рабочие дни и перерывы</b><span>›</span></div><div class="small muted">График, выходные и исключения</div></button></div>`}
function bookingLine(b){const s=service(b.serviceId);return `<div class="list-item"><div class="row"><div><b>${esc(b.personName)}</b><div class="small muted">${fmtDate(b.date)} · ${b.start}–${b.end} · ${esc(s?.name||'Услуга')}</div></div><span class="badge ${b.status==='cancelled'?'red':'green'}">${statusName(b.status)}</span></div></div>`}
function statusName(s){return ({pending:'Ожидает',confirmed:'Подтверждена',completed:'Завершена',cancelled:'Отменена',no_show:'Неявка'})[s]||s}
function services(){return `<div class="step">Мастер → Услуги и прайс</div><div class="row"><h2>Услуги и прайс</h2><button class="secondary" data-action="add-service">+ Добавить</button></div>${db.services.map(s=>`<div class="card"><div class="row"><div><b>${esc(s.name)}</b><div class="small muted">${s.duration} минут · ${money(s.price)}</div></div><span class="badge ${s.active?'green':'red'}">${s.active?'Активна':'Выключена'}</span></div><div class="two" style="margin-top:10px"><button class="secondary" data-edit-service="${s.id}">Изменить</button><button class="secondary" data-toggle-service="${s.id}">${s.active?'Выключить':'Включить'}</button></div></div>`).join('')}<div class="notice">Цена и длительность сохраняются в самой записи на момент бронирования. Изменение прайса не меняет старые записи.</div>`}
function schedule(){const names=['Вс','Пн','Вт','Ср','Чт','Пт','Сб'];return `<div class="step">Мастер → Расписание</div><h2>Рабочие дни</h2>${[1,2,3,4,5,6,0].map(d=>{const h=db.hours[d];return `<div class="card"><div class="row"><b>${names[d]}</b>${h?`<span class="badge green">${h[0]}–${h[1]}</span>`:'<span class="badge">Выходной</span>'}</div><div class="two" style="margin-top:10px"><input data-hour-day="${d}" data-part="0" type="time" value="${h?h[0]:'10:00'}"><input data-hour-day="${d}" data-part="1" type="time" value="${h?h[1]:'20:00'}"></div><label class="check"><input type="checkbox" data-working-day="${d}" ${h?'checked':''}> Работаю в этот день</label></div>`}).join('')}<h2>Перерывы</h2><div class="card">${db.breaks.map(b=>`<div class="list-item"><div class="row"><span>${names[b.day]} · ${b.start}–${b.end}</span><button class="secondary" data-delete-break="${b.id}">Удалить</button></div></div>`).join('')}<button class="primary" data-action="add-break">+ Добавить перерыв</button></div><h2>Исключения</h2><div class="card">${Object.entries(db.exceptions).length?Object.entries(db.exceptions).map(([date,x])=>`<div class="list-item"><div class="row"><span>${fmtDate(date)} · ${x.type==='dayoff'?'выходной':x.hours.join('–')}</span><button class="secondary" data-delete-exception="${date}">Удалить</button></div></div>`).join(''):'<div class="empty">Нет исключений</div>'}<button class="primary" data-action="add-exception">+ Добавить изменение дня</button></div><div class="card"><b>Правила записи</b><div class="small muted" style="margin-top:7px">Шаг: ${db.master.slotStep} мин · минимум до записи: ${db.master.bookingNotice/60} ч · вперёд: ${db.master.bookingHorizon} дней · отмена: ${db.master.cancelBefore/60} ч</div></div>`}
function calendar(){const dates=Array.from({length:14},(_,i)=>addDays(i));return `<div class="row"><h2>Календарь</h2><button class="secondary" data-mode-client="1">Открыть запись</button></div><div class="calendar-days">${dates.map(d=>`<button class="day ${d===state.date?'active':''}" data-date="${d}"><div class="dow">${new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'short'})}</div><div class="num">${new Date(d+'T12:00:00').getDate()}</div></button>`).join('')}</div><div class="card"><b>${fmtDate(state.date)}</b>${db.bookings.filter(b=>b.date===state.date&&b.status!=='cancelled').length?db.bookings.filter(b=>b.date===state.date&&b.status!=='cancelled').sort((a,b)=>a.start.localeCompare(b.start)).map(bookingLine).join(''):'<div class="empty">Нет записей</div>'}</div>`}
function renderClient(){if(state.screen==='confirm')return confirmScreen();return `<div class="hero"><h1>Записаться онлайн</h1><p>${esc(db.master.name)} · выберите услугу, дату и удобное время.</p></div><div class="step">Шаг ${state.service?2:1} из 3${state.service?' · '+esc(state.service.name):''}</div><h2>${state.service?'Выберите дату и время':'Выберите услугу'}</h2>${!state.service?db.services.filter(s=>s.active).map(s=>`<button class="service" data-service="${s.id}"><div class="row"><div><div class="service-title">${esc(s.name)}</div><div class="service-meta">${s.duration} минут</div></div><div class="price">${money(s.price)}</div></div></button>`).join(''):clientDateTime()}`}
function clientDateTime(){const dates=Array.from({length:14},(_,i)=>addDays(i));const sl=slots(state.date,state.service);return `<button class="secondary" data-action="back-service">← Другая услуга</button><div class="section-title">Дата</div><div class="calendar-days">${dates.map(d=>`<button class="day ${d===state.date?'active':''}" data-date="${d}"><div class="dow">${new Date(d+'T12:00:00').toLocaleDateString('ru-RU',{weekday:'short'})}</div><div class="num">${new Date(d+'T12:00:00').getDate()}</div></button>`).join('')}</div><div class="section-title">Свободное время</div>${sl.length?`<div class="grid">${sl.map(t=>`<button class="slot ${state.slot===t?'active':''}" data-slot="${t}">${t}</button>`).join('')}</div>`:'<div class="notice">На эту дату подходящего времени нет. Выберите другой день.</div>'}${state.slot?`<div style="margin-top:16px"><button class="primary" data-action="continue">Продолжить</button></div>`:''}`}
function confirmScreen(){return `<div class="success"><div class="success-icon">✓</div><h2>Проверьте запись</h2><p class="muted">Перед созданием запись будет повторно проверена.</p></div><div class="card"><div class="list-item"><b>Услуга</b><div class="muted">${esc(state.service.name)}</div></div><div class="list-item"><b>Дата</b><div class="muted">${fmtDate(state.date)}</div></div><div class="list-item"><b>Время</b><div class="muted">${state.slot}–${hm(mins(state.slot)+state.service.duration)}</div></div><div class="list-item"><b>Стоимость</b><div class="muted">${money(state.service.price)}</div></div></div><button class="primary" data-action="book">Подтвердить запись</button><div style="height:8px"></div><button class="secondary" style="width:100%" data-action="back-time">← Изменить</button>`}
function bind(){document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{state.screen=b.dataset.screen;render()});document.querySelectorAll('[data-toggle-mode]').forEach(b=>b.onclick=()=>{state.mode=state.mode==='master'?'client':'master';state.screen='home';state.service=null;state.slot=null;render()});document.querySelectorAll('[data-mode-client]').forEach(b=>b.onclick=()=>{state.mode='client';state.screen='home';state.service=null;state.slot=null;render()});document.querySelectorAll('[data-service]').forEach(b=>b.onclick=()=>{state.service=service(b.dataset.service);state.slot=null;state.date=addDays(0);render()});document.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{state.date=b.dataset.date;state.slot=null;render()});document.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{state.slot=b.dataset.slot;render()});document.querySelectorAll('[data-toggle-service]').forEach(b=>b.onclick=()=>{const s=service(b.dataset.toggleService);s.active=!s.active;save();render()});document.querySelectorAll('[data-edit-service]').forEach(b=>b.onclick=()=>editService(b.dataset.editService));document.querySelectorAll('[data-delete-break]').forEach(b=>b.onclick=()=>{db.breaks=db.breaks.filter(x=>x.id!==b.dataset.deleteBreak);save();render()});document.querySelectorAll('[data-delete-exception]').forEach(b=>b.onclick=()=>{delete db.exceptions[b.dataset.deleteException];save();render()});document.querySelectorAll('[data-working-day]').forEach(b=>b.onchange=()=>{const d=Number(b.dataset.workingDay);if(b.checked){const a=document.querySelector(`[data-hour-day="${d}"][data-part="0"]`).value;const z=document.querySelector(`[data-hour-day="${d}"][data-part="1"]`).value;db.hours[d]=[a,z]}else db.hours[d]=null;save();render()});document.querySelectorAll('[data-hour-day]').forEach(b=>b.onchange=()=>{const d=Number(b.dataset.hourDay);if(db.hours[d])db.hours[d][Number(b.dataset.part)]=b.value;save()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action))}
function action(a){if(a==='back-service'){state.service=null;state.slot=null;render()}if(a==='back-time'){state.screen='home';render()}if(a==='continue'){state.screen='confirm';render()}if(a==='book')createBooking();if(a==='add-service')addService();if(a==='add-break')addBreak();if(a==='add-exception')addException()}
function addService(){const name=prompt('Название услуги','Новая услуга');if(!name)return;const price=Number(prompt('Стоимость, ₽','3000'));const duration=Number(prompt('Длительность в минутах','60'));if(!price||!duration)return;db.services.push({id:'s'+Date.now(),name,duration,price,active:true});save();render()}
function editService(id){const s=service(id);const name=prompt('Название услуги',s.name);if(name===null)return;const price=Number(prompt('Стоимость, ₽',s.price));const duration=Number(prompt('Длительность в минутах',s.duration));if(name&&price>0&&duration>0){s.name=name;s.price=price;s.duration=duration;save();render()}}
function addBreak(){const date=prompt('День недели: 1=Пн, 2=Вт, 3=Ср, 4=Чт, 5=Пт, 6=Сб, 0=Вс','1');const start=prompt('Начало','14:00');const end=prompt('Конец','15:00');if(date===null||!start||!end)return;db.breaks.push({id:'b'+Date.now(),day:Number(date),start,end});save();render()}
function addException(){const date=prompt('Дата в формате ГГГГ-ММ-ДД',addDays(7));if(!date)return;const dayoff=confirm('Сделать этот день выходным? Нажмите «Отмена», чтобы задать сокращённый день.');if(dayoff)db.exceptions[date]={type:'dayoff'};else{const start=prompt('Начало работы','10:00');const end=prompt('Конец работы','16:00');if(!start||!end)return;db.exceptions[date]={type:'hours',hours:[start,end]}}save();render()}
function createBooking(){const fresh=slots(state.date,state.service);if(!fresh.includes(state.slot)){alert('Это время уже занято. Выберите другой слот.');state.screen='home';state.slot=null;render();return}const end=hm(mins(state.slot)+state.service.duration);db.bookings.push({id:'bk'+Date.now(),personId:db.person.id,personName:db.person.name,serviceId:state.service.id,date:state.date,start:state.slot,end,price:state.service.price,duration:state.service.duration,status:'confirmed'});save();state.screen='home';state.service=null;state.slot=null;alert('Запись создана.');render()}
render();
