const PAGES = ['journal', 'timetable', 'management', 'chat', 'settings', 'services'];
const state = { page: 'management', year: 2026, month: 7, selectedDates: new Set() };
const app = document.getElementById('app');
const navItems = [['journal','▤','Журнал'],['timetable','▦','График'],['management','⌂','Управление'],['chat','◌','Чат'],['settings','⚙','Настройки']];
function nav(){return `<nav class="bottom" aria-label="Основная навигация">${navItems.map(([page,icon,label])=>`<button class="nav ${state.page===page?'active':''}" data-page="${page}" type="button"><span class="nav-icon">${icon}</span><span>${label}</span></button>`).join('')}</nav>`}
function shell(content){return `<div class="shell"><header class="topbar"><div class="brand">CoBook</div><div class="subtitle">Кабинет мастера</div></header><main class="content">${content}</main>${nav()}</div>`}
function management(){return shell(`<section class="hero"><div class="eyebrow">КАБИНЕТ МАСТЕРА</div><h1>Управление</h1><p>Основной рабочий экран мастера.</p></section><section class="section-grid"><button class="menu-card" data-page="services" type="button"><span class="menu-icon">₽</span><b>Прайс</b><span>Услуги и стоимость</span></button></section>`)}
function journal(){return shell(`<section class="page-head"><div class="eyebrow">РАБОТА С ЖУРНАЛОМ</div><h1>Журнал</h1><p>Экран журнала записей.</p></section><div class="tabs"><button class="tab active" type="button">День</button><button class="tab" type="button">Месяц</button><button class="tab" type="button">Список</button></div><section class="panel"><div class="panel-title">Сегодня</div><div class="empty">Записи будут отображаться здесь.</div></section><button class="primary" type="button">Новая запись</button>`)}
function timetable(){const monthName=new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(new Date(state.year,state.month,1));return shell(`<section class="page-head"><div class="eyebrow">ФОРМИРОВАНИЕ ГРАФИКА</div><h1>График</h1><p>Выберите рабочие даты.</p></section><section class="calendar-panel"><div class="period-row year-row"><button class="period-arrow" data-year="prev" type="button">‹</button><b>${state.year}</b><button class="period-arrow" data-year="next" type="button">›</button></div><div class="period-row month-row"><button class="period-arrow" data-month="prev" type="button">‹</button><b>${monthName.charAt(0).toUpperCase()+monthName.slice(1)}</b><button class="period-arrow" data-month="next" type="button">›</button></div><div class="calendar-grid">${calendarDays(state.year,state.month)}</div><section class="panel work-interval"><div class="panel-title">Рабочий интервал</div><div class="time-row"><div><span>Начало</span><b>10:00</b></div><div><span>Окончание</span><b>20:00</b></div></div><button class="primary full" type="button">Применить рабочий день</button></section></section>`)}
function dateKey(year,month,day){return `${year}-${month+1}-${day}`}
function calendarDays(year,month){const labels=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const first=new Date(year,month,1);const offset=(first.getDay()+6)%7;const daysInMonth=new Date(year,month+1,0).getDate();const daysPrev=new Date(year,month,0).getDate();const cells=[];labels.forEach(label=>cells.push(`<div class="calendar-weekday">${label}</div>`));for(let i=offset-1;i>=0;i--)cells.push(`<button class="calendar-day outside" type="button">${daysPrev-i}</button>`);for(let day=1;day<=daysInMonth;day++){const key=dateKey(year,month,day);cells.push(`<button class="calendar-day${state.selectedDates.has(key)?' selected':''}" data-date="${key}" type="button">${day}</button>`)}let nextDay=1;while(cells.length%7!==0)cells.push(`<button class="calendar-day outside" type="button">${nextDay++}</button>`);return cells.join('')}
function services(){return shell(`<section class="page-head"><div class="eyebrow">УПРАВЛЕНИЕ · ПРАЙС</div><h1>Прайс</h1><p>Услуги и стоимость.</p></section><section class="panel"><div class="empty">Список услуг будет добавлен после утверждения интерфейса.</div></section>`)}
function chat(){return shell(`<section class="page-head"><div class="eyebrow">КОММУНИКАЦИЯ</div><h1>Чат</h1><p>Подключение к чат-боту для рассылок, уведомлений и общения.</p></section>`)}
function settings(){return shell(`<section class="page-head"><div class="eyebrow">РАБОЧИЕ НАСТРОЙКИ</div><h1>Настройки</h1><p>Рабочие настройки кабинета мастера.</p></section>`)}
function render(){const views={journal,timetable,management,chat,settings,services};app.innerHTML=(views[state.page]||management)()}
app.addEventListener('click',event=>{const pageTarget=event.target.closest('[data-page]');if(pageTarget){state.page=pageTarget.dataset.page;render();return}const dateTarget=event.target.closest('[data-date]');if(dateTarget){const key=dateTarget.dataset.date;state.selectedDates.has(key)?state.selectedDates.delete(key):state.selectedDates.add(key);render();return}const yearTarget=event.target.closest('[data-year]');if(yearTarget){state.year+=yearTarget.dataset.year==='next'?1:-1;render();return}const monthTarget=event.target.closest('[data-month]');if(monthTarget){state.month+=monthTarget.dataset.month==='next'?1:-1;if(state.month<0){state.month=11;state.year--}if(state.month>11){state.month=0;state.year++}render()}});render();
