const DOCUMENT_TYPES=[
  {id:'pdn',name:'Политика и согласия ПДН',description:'Документы по обработке персональных данных'},
  {id:'mailing',name:'Согласия на рассылку',description:'Согласие на получение сообщений и рассылок'}
];
const documentStoreKey='cobook_documents_v1';
function readDocuments(){try{return JSON.parse(localStorage.getItem(documentStoreKey)||'[]')}catch(_){return []}}
function writeDocuments(v){localStorage.setItem(documentStoreKey,JSON.stringify(v))}
function esc(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]))}
function documentCards(){const saved=readDocuments();return DOCUMENT_TYPES.map(type=>{const versions=saved.filter(x=>x.documentType===type.id).sort((a,b)=>b.version-a.version);const current=versions[0];return `<article class="document-card"><div class="document-card-main"><div class="document-icon">PDF</div><div class="document-info"><b>${type.name}</b><small>${type.description}</small>${current?`<span class="document-status">Версия ${current.version} · ${esc(current.date)}</span>`:'<span class="document-status empty-status">Документ не загружен</span>'}</div></div><div class="document-card-actions">${current?`<button class="document-secondary" data-document-action="history" data-document-type="${type.id}" type="button">История</button><button class="document-secondary" data-document-action="replace" data-document-type="${type.id}" type="button">Заменить PDF</button>`:`<button class="primary document-upload-button" data-document-action="add" data-document-type="${type.id}" type="button">Добавить PDF</button>`}</div></article>`}).join('')}
function documents(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ · ДОКУМЕНТЫ</div><h1>Документы</h1><p>Здесь хранятся действующие документы и история их версий.</p></section><section class="documents-list">${documentCards()}</section><button class="document-add-type" data-document-action="new-type" type="button">＋ Добавить другой документ</button><button class="document-back-button" data-action="navigate" data-page="settings" type="button">Назад</button>`)}
function documentUploadModal(typeId){const type=DOCUMENT_TYPES.find(x=>x.id===typeId);return `<div class="service-overlay" data-modal="document" data-document-type="${typeId}"><div class="service-sheet document-sheet"><div class="service-sheet-head"><b>${type?type.name:'Новый документ'}</b><button class="service-close" data-modal-action="close" type="button">×</button></div><label class="document-file-field"><input data-document-file type="file" accept="application/pdf"><span>Выбрать PDF-файл</span><small>Новая загрузка станет новой версией. Старые версии сохраняются.</small></label><button class="primary full" data-modal-action="save-document" type="button">Сохранить PDF</button></div></div>`}
function documentHistory(typeId){const type=DOCUMENT_TYPES.find(x=>x.id===typeId);const rows=readDocuments().filter(x=>x.documentType===typeId).sort((a,b)=>b.version-a.version);return `<div class="service-overlay" data-modal="document-history"><div class="service-sheet document-sheet"><div class="service-sheet-head"><b>История · ${type?type.name:'Документ'}</b><button class="service-close" data-modal-action="close" type="button">×</button></div><div class="document-history">${rows.length?rows.map(x=>`<div class="document-version"><span><b>Версия ${x.version}</b><small>${esc(x.date)} · ${esc(x.fileName)}</small></span><button class="document-secondary" data-document-action="open-version" data-document-id="${x.id}" type="button">Открыть</button></div>`).join(''):'<div class="empty">История пока пуста.</div>'}</div></div></div>`}
function saveDocumentFile(typeId,file){if(!file||file.type!=='application/pdf')return;const reader=new FileReader();reader.onload=()=>{const all=readDocuments(),versions=all.filter(x=>x.documentType===typeId),version=versions.length?Math.max(...versions.map(x=>x.version))+1:1;all.push({id:`doc_${Date.now()}`,documentType:typeId,version,fileName:file.name,date:new Intl.DateTimeFormat('ru-RU').format(new Date()),dataUrl:reader.result});writeDocuments(all);document.querySelector('[data-modal="document"]')?.remove();renderDocuments();};reader.readAsDataURL(file)}
function renderDocuments(){const app=document.getElementById('app');if(app)app.innerHTML=documents()}
function documentAction(a,e){const typeId=e.dataset.documentType;if(a==='add'||a==='replace'){document.body.insertAdjacentHTML('beforeend',documentUploadModal(typeId));return}if(a==='history'){document.body.insertAdjacentHTML('beforeend',documentHistory(typeId));return}if(a==='open-version'){const item=readDocuments().find(x=>x.id===e.dataset.documentId);if(item?.dataUrl){const w=window.open();if(w){w.document.write(`<iframe src="${item.dataUrl}" style="border:0;width:100%;height:100vh"></iframe>`);w.document.close()}}return}if(a==='new-type'){return alert('Дополнительные типы документов будут подключены отдельным этапом.')}}
document.addEventListener('change',e=>{const input=e.target.closest('[data-document-file]');if(!input)return;const modal=input.closest('[data-modal="document"]');if(modal)modal.dataset.fileReady=input.files?.[0]?'1':'';if(input.files?.[0])input.closest('.document-file-field').querySelector('span').textContent=input.files[0].name},true);
document.addEventListener('click',e=>{const a=e.target.closest('[data-document-action]');if(a){e.preventDefault();e.stopImmediatePropagation();return documentAction(a.dataset.documentAction,a)}const save=e.target.closest('[data-modal-action="save-document"]');if(save){e.preventDefault();e.stopImmediatePropagation();const modal=save.closest('[data-modal="document"]'),input=modal?.querySelector('[data-document-file]');return saveDocumentFile(modal?.dataset.documentType,input?.files?.[0])}const close=e.target.closest('[data-modal-action="close"]');if(close){const modal=close.closest('[data-modal]');if(modal)modal.remove()}},true);
window.documents=documents;
window.renderDocuments=renderDocuments;
