(function(){
  const KEY='cobook_loyalty_programs';
  const root=()=>document.getElementById('app');
  const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}};
  const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const procedures=()=>Array.isArray(window.state?.procedures)?window.state.procedures:JSON.parse(localStorage.getItem('cobook_procedures')||'[]');
  const shellLocal=html=>`<div class="shell"><header class="topbar"><div class="brand">CoBook</div><div class="subtitle">Кабинет мастера</div></header><main class="content">${html}</main><nav class="bottom"><button class="nav" data-action="navigate" data-page="journal" type="button"><span class="nav-icon">▤</span><span>Журнал</span></button><button class="nav" data-action="navigate" data-page="timetable" type="button"><span class="nav-icon">▦</span><span>График</span></button><button class="nav" data-action="navigate" data-page="maine" type="button"><span class="nav-icon">⌂</span><span>Главная</span></button><button class="nav" data-action="navigate" data-page="chat" type="button"><span class="nav-icon">◌</span><span>Чат</span></button><button class="nav" data-action="navigate" data-page="settings" type="button"><span class="nav-icon">⚙</span><span>Настройки</span></button></nav></div>`;
  function list(){const a=read();return shellLocal(`<section class="page-head"><button class="back-button" data-loyalty="settings" type="button">‹ Настройки</button><div class="eyebrow">НАСТРОЙКИ · ЛОЯЛЬНОСТЬ</div><h1>Лояльность</h1></section><div class="loyalty-list">${a.length?a.map((p,i)=>`<button class="loyalty-card" data-loyalty-edit="${i}" type="button"><span><b>${esc(p.name)}</b><small>${esc(p.conditionText||'')} · ${esc(p.rewardText||'')}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Программ пока нет</div>'}</div><button class="primary full" data-loyalty-create type="button">Создать программу</button>`)}
  function rewardEditor(p){
    const reward=p.reward||'discount';
    const procList=procedures();
    const selectedProc=p.freeMode==='procedure'?(p.freeProcedureIndex??''):'';
    return `<label class="service-field"><span>Тип</span><select data-lf="reward"><option value="discount" ${reward==='discount'?'selected':''}>Скидка, %</option><option value="free" ${reward==='free'?'selected':''}>Бесплатно</option><option value="money" ${reward==='money'||reward==='fixed'?'selected':''}>Деньги</option></select></label><div data-reward-fields>${rewardFields(p,reward,procList,selectedProc)}</div>`;
  }
  function rewardFields(p,reward,procList,selectedProc){
    if(reward==='free') return `<div class="loyalty-subblock"><b>Что дарится бесплатно?</b><div class="loyalty-choice"><label><input type="radio" name="free-mode" value="procedure" data-lf="free-mode" ${p.freeMode!=='manual'?'checked':''}> Процедура</label><label><input type="radio" name="free-mode" value="manual" data-lf="free-mode" ${p.freeMode==='manual'?'checked':''}> Другое</label></div><div data-free-detail>${p.freeMode==='manual'?`<label class="service-field"><span>Что дарите</span><input data-lf="free-manual" value="${esc(p.freeManual||'')}" placeholder="Например, шампунь"></label>`:`<label class="service-field"><span>Процедура</span><select data-lf="free-procedure"><option value="">Выберите процедуру</option>${procList.map((x,i)=>`<option value="${i}" ${String(selectedProc)===String(i)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`}</div></div>`;
    if(reward==='money'||reward==='fixed') return `<label class="service-field"><span>Сумма</span><input data-lf="money" type="number" min="0" step="1" value="${esc(p.money??p.value??'')}" placeholder="500"><small>₽</small></label>`;
    return `<label class="service-field"><span>Размер скидки</span><input data-lf="discount" type="number" min="0" max="100" step="1" value="${esc(p.discount??p.value??'')}" placeholder="20"><small>%</small></label>`;
  }
  function editor(index){const a=read(),p=index===null?{name:'',condition:'visits',threshold:10,reward:'discount',discount:20,scope:'all',freeMode:'procedure'}:{...a[index]};return shellLocal(`<section class="page-head"><button class="back-button" data-loyalty="list" type="button">‹ Лояльность</button><div class="eyebrow">ЛОЯЛЬНОСТЬ · ПРОГРАММА</div><h1>${index===null?'Новая программа':'Изменить программу'}</h1></section><section class="loyalty-form"><label class="service-field"><span>Название программы</span><input data-lf="name" value="${esc(p.name)}" placeholder="Например, Каждая 10-я стрижка"></label><div class="loyalty-block"><b>Условие</b><label class="service-field"><span>Событие</span><select data-lf="condition"><option value="visits" ${p.condition==='visits'?'selected':''}>Количество посещений</option><option value="spent" ${p.condition==='spent'?'selected':''}>Сумма покупок</option></select></label><label class="service-field"><span>${p.condition==='spent'?'Сумма покупок':'Количество посещений'}</span><input data-lf="threshold" type="number" min="1" value="${esc(p.threshold)}"></label></div><div class="loyalty-block"><b>Награда</b>${rewardEditor(p)}</div><div class="loyalty-block"><b>Для кого</b><label class="service-field"><select data-lf="scope"><option value="all" ${p.scope==='all'?'selected':''}>Всех клиентов</option><option value="selected" ${p.scope==='selected'?'selected':''}>Выбранных клиентов</option></select></label></div><button class="primary full" data-loyalty-save="${index===null?'':index}" type="button">Сохранить программу</button>${index!==null?`<button class="danger full" data-loyalty-delete="${index}" type="button">Удалить программу</button>`:''}</section>`)}
  function showList(){const r=root();if(r)r.innerHTML=list()}
  function showEditor(index=null){const r=root();if(r)r.innerHTML=editor(index)}
  function rerenderReward(){const reward=document.querySelector('[data-lf="reward"]')?.value||'discount';const host=document.querySelector('[data-reward-fields]');if(!host)return;const old={reward};const mode=document.querySelector('[data-lf="free-mode"]:checked')?.value;const proc=document.querySelector('[data-lf="free-procedure"]')?.value;const manual=document.querySelector('[data-lf="free-manual"]')?.value;const value=document.querySelector('[data-lf="discount"]')?.value||document.querySelector('[data-lf="money"]')?.value||'';old.freeMode=mode;old.freeProcedureIndex=proc;old.freeManual=manual;old.discount=value;old.money=value;host.innerHTML=rewardFields(old,reward,procedures(),proc);}
  document.addEventListener('change',function(e){
    if(e.target.matches('[data-lf="reward"]')){rerenderReward();return;}
    if(e.target.matches('[data-lf="free-mode"]')){const reward=document.querySelector('[data-lf="reward"]')?.value||'free';const host=document.querySelector('[data-reward-fields]');if(host){const p={reward,freeMode:e.target.value,freeProcedureIndex:document.querySelector('[data-lf="free-procedure"]')?.value,freeManual:document.querySelector('[data-lf="free-manual"]')?.value};host.innerHTML=rewardFields(p,reward,procedures(),p.freeProcedureIndex)}}
    if(e.target.matches('[data-lf="condition"]')){const label=document.querySelector('[data-lf="threshold"]')?.previousElementSibling;if(label)label.textContent=e.target.value==='spent'?'Сумма покупок':'Количество посещений';}
  });
  document.addEventListener('click',function(e){
    const create=e.target.closest('[data-loyalty-create],[data-action="loyalty-create"]');if(create){e.preventDefault();e.stopImmediatePropagation();showEditor(null);return;}
    const edit=e.target.closest('[data-loyalty-edit]');if(edit){e.preventDefault();e.stopImmediatePropagation();showEditor(Number(edit.dataset.loyaltyEdit));return;}
    const saveBtn=e.target.closest('[data-loyalty-save]');if(saveBtn){e.preventDefault();e.stopImmediatePropagation();const name=document.querySelector('[data-lf="name"]')?.value.trim();if(!name){alert('Введите название программы');return;}const condition=document.querySelector('[data-lf="condition"]')?.value||'visits';const threshold=Math.max(1,Number(document.querySelector('[data-lf="threshold"]')?.value)||1);const reward=document.querySelector('[data-lf="reward"]')?.value||'discount';let item={name,condition,threshold,reward,scope:document.querySelector('[data-lf="scope"]')?.value||'all'};if(reward==='discount'){const discount=Math.min(100,Math.max(0,Number(document.querySelector('[data-lf="discount"]')?.value)||0));item.discount=discount;item.rewardText=`скидка ${discount}%`;}else if(reward==='free'){const freeMode=document.querySelector('[data-lf="free-mode"]:checked')?.value||'procedure';item.freeMode=freeMode;if(freeMode==='procedure'){const i=document.querySelector('[data-lf="free-procedure"]')?.value;if(i===''){alert('Выберите процедуру или выберите «Другое»');return;}item.freeProcedureIndex=Number(i);item.freeText=procedures()[Number(i)]?.name||'';}else{const text=document.querySelector('[data-lf="free-manual"]')?.value.trim()||'';if(!text){alert('Укажите, что дарится бесплатно');return;}item.freeManual=text;item.freeText=text;}item.rewardText=`бесплатно: ${item.freeText}`;}else{const money=Math.max(0,Number(document.querySelector('[data-lf="money"]')?.value)||0);if(!money){alert('Укажите сумму');return;}item.money=money;item.rewardText=`деньги ${money} ₽`;}item.conditionText=condition==='visits'?`${threshold} посещений`:`${threshold} ₽ покупок`;const a=read();const raw=saveBtn.dataset.loyaltySave;if(raw==='')a.push(item);else a[Number(raw)]=item;write(a);showList();return;}
    const del=e.target.closest('[data-loyalty-delete]');if(del){e.preventDefault();e.stopImmediatePropagation();const a=read();a.splice(Number(del.dataset.loyaltyDelete),1);write(a);showList();return;}
    const back=e.target.closest('[data-loyalty]');if(back){e.preventDefault();e.stopImmediatePropagation();if(back.dataset.loyalty==='settings'&&typeof window.render==='function'){state.page='settings';window.render();}else showList();return;}
    const loyaltyNav=e.target.closest('[data-action="navigate"][data-page="loyalty"]');if(loyaltyNav){e.preventDefault();e.stopImmediatePropagation();showList();return;}
  },true);
})();