(function(){
  const KEY='cobook_loyalty_programs';
  const root=()=>document.getElementById('app');
  const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch(e){return[]}};
  const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  const shellLocal=html=>`<div class="shell"><header class="topbar"><div class="brand">CoBook</div><div class="subtitle">Кабинет мастера</div></header><main class="content">${html}</main><nav class="bottom"><button class="nav" data-action="navigate" data-page="journal" type="button"><span class="nav-icon">▤</span><span>Журнал</span></button><button class="nav" data-action="navigate" data-page="timetable" type="button"><span class="nav-icon">▦</span><span>График</span></button><button class="nav" data-action="navigate" data-page="maine" type="button"><span class="nav-icon">⌂</span><span>Главная</span></button><button class="nav" data-action="navigate" data-page="chat" type="button"><span class="nav-icon">◌</span><span>Чат</span></button><button class="nav" data-action="navigate" data-page="settings" type="button"><span class="nav-icon">⚙</span><span>Настройки</span></button></nav></div>`;
  function list(){const a=read();return shellLocal(`<section class="page-head"><button class="back-button" data-loyalty="settings" type="button">‹ Настройки</button><div class="eyebrow">НАСТРОЙКИ · ЛОЯЛЬНОСТЬ</div><h1>Лояльность</h1></section><div class="loyalty-list">${a.length?a.map((p,i)=>`<button class="loyalty-card" data-loyalty-edit="${i}" type="button"><span><b>${esc(p.name)}</b><small>${esc(p.conditionText)} · ${esc(p.rewardText)}</small></span><span>›</span></button>`).join(''):'<div class="loyalty-empty">Программ пока нет</div>'}</div><button class="primary full" data-loyalty-create type="button">Создать программу</button>`)}
  function editor(index){const a=read(),p=index===null?{name:'',condition:'visits',threshold:10,reward:'discount',value:100,scope:'all'}:a[index];return shellLocal(`<section class="page-head"><button class="back-button" data-loyalty="list" type="button">‹ Лояльность</button><div class="eyebrow">ЛОЯЛЬНОСТЬ · ПРОГРАММА</div><h1>${index===null?'Новая программа':'Изменить программу'}</h1></section><section class="loyalty-form"><label class="service-field"><span>Название программы</span><input data-lf="name" value="${esc(p.name)}" placeholder="Например, Каждая 10-я стрижка"></label><div class="loyalty-block"><b>Условие</b><label class="service-field"><span>Событие</span><select data-lf="condition"><option value="visits" ${p.condition==='visits'?'selected':''}>Количество посещений</option><option value="spent" ${p.condition==='spent'?'selected':''}>Сумма покупок</option></select></label><label class="service-field"><span>Значение</span><input data-lf="threshold" type="number" min="1" value="${esc(p.threshold)}"></label></div><div class="loyalty-block"><b>Награда</b><label class="service-field"><span>Тип</span><select data-lf="reward"><option value="discount" ${p.reward==='discount'?'selected':''}>Скидка, %</option><option value="free" ${p.reward==='free'?'selected':''}>Бесплатно</option><option value="fixed" ${p.reward==='fixed'?'selected':''}>Фиксированная цена</option></select></label><label class="service-field"><span>Значение</span><input data-lf="value" type="number" min="0" value="${esc(p.value)}"></label></div><div class="loyalty-block"><b>Для кого</b><label class="service-field"><select data-lf="scope"><option value="all" ${p.scope==='all'?'selected':''}>Всех клиентов</option><option value="selected" ${p.scope==='selected'?'selected':''}>Выбранных клиентов</option></select></label></div><button class="primary full" data-loyalty-save="${index===null?'':index}" type="button">Сохранить программу</button>${index!==null?`<button class="danger full" data-loyalty-delete="${index}" type="button">Удалить программу</button>`:''}</section>`)}
  function showList(){const r=root();if(r)r.innerHTML=list()}
  function showEditor(index=null){const r=root();if(r)r.innerHTML=editor(index)}
  document.addEventListener('click',function(e){
    const create=e.target.closest('[data-loyalty-create]');
    if(create){e.preventDefault();e.stopImmediatePropagation();showEditor(null);return;}
    const edit=e.target.closest('[data-loyalty-edit]');
    if(edit){e.preventDefault();e.stopImmediatePropagation();showEditor(Number(edit.dataset.loyaltyEdit));return;}
    const saveBtn=e.target.closest('[data-loyalty-save]');
    if(saveBtn){e.preventDefault();e.stopImmediatePropagation();const name=document.querySelector('[data-lf="name"]')?.value.trim();if(!name){alert('Введите название программы');return;}const condition=document.querySelector('[data-lf="condition"]')?.value||'visits';const threshold=Math.max(1,Number(document.querySelector('[data-lf="threshold"]')?.value)||1);const reward=document.querySelector('[data-lf="reward"]')?.value||'discount';const value=Math.max(0,Number(document.querySelector('[data-lf="value"]')?.value)||0);const scope=document.querySelector('[data-lf="scope"]')?.value||'all';const conditionText=condition==='visits'?`${threshold} посещений`:`${threshold} ₽ покупок`;const rewardText=reward==='discount'?`скидка ${value}%`:reward==='free'?'бесплатно':`цена ${value} ₽`;const item={name,condition,threshold,reward,value,scope,conditionText,rewardText};const a=read();const raw=saveBtn.dataset.loyaltySave;if(raw==='')a.push(item);else a[Number(raw)]=item;write(a);showList();return;}
    const del=e.target.closest('[data-loyalty-delete]');
    if(del){e.preventDefault();e.stopImmediatePropagation();const a=read();a.splice(Number(del.dataset.loyaltyDelete),1);write(a);showList();return;}
    const back=e.target.closest('[data-loyalty]');
    if(back){e.preventDefault();e.stopImmediatePropagation();if(back.dataset.loyalty==='settings'&&typeof window.render==='function'){state.page='settings';window.render();}else showList();return;}
    const loyaltyNav=e.target.closest('[data-action="navigate"][data-page="loyalty"]');
    if(loyaltyNav){e.preventDefault();e.stopImmediatePropagation();showList();return;}
  },true);
})();