function nextClientId(){const used=new Set(state.clients.map(c=>String(c.client_id)));for(let n=1;n<=9999;n++){const id=String(n).padStart(4,'0');if(!used.has(id))return id}return null}
function clientCard(c){const name=c.name||'Без имени';const count=Array.isArray(c.telegram_ids)?c.telegram_ids.length:0;return `<button class="client-card" data-action="open-client" data-client-id="${c.client_id}" type="button"><span class="client-card-id">${c.client_id}</span><span class="client-card-main"><b>${name}</b><small>${count} Telegram ID</small></span><span class="client-card-arrow">›</span></button>`}
function clients(){if(state.clientView==='profile'){const c=state.clients.find(x=>x.client_id===state.selectedClientId);if(!c){state.clientView='list';state.selectedClientId=null;return clients()}const ids=Array.isArray(c.telegram_ids)?c.telegram_ids:[];return shell(`<section class="page-head"><button class="back-button" data-action="back-clients" type="button">‹ Клиенты</button><div class="eyebrow">КЛИЕНТ · ${c.client_id}</div><h1>${c.name||'Без имени'}</h1></section><section class="client-profile"><div class="client-id-box"><span>Client ID</span><b>${c.client_id}</b></div><label class="client-field"><span>Имя</span><input data-client-field="name" value="${(c.name||'').replace(/"/g,'&quot;')}"></label><button class="primary full" data-action="save-client" data-client-id="${c.client_id}" type="button">Сохранить</button><div class="client-section"><div class="client-section-head"><b>Telegram ID</b><span>${ids.length}</span></div>${ids.map((id,i)=>`<div class="telegram-row"><span>${id}</span><button data-action="remove-telegram" data-client-id="${c.client_id}" data-telegram-index="${i}" type="button">Удалить</button></div>`).join('')}<div class="telegram-add"><input data-telegram-input placeholder="Telegram ID"><button class="primary" data-action="add-telegram" data-client-id="${c.client_id}" type="button">Связать</button></div></div></section>`,false)}return shell(`<section class="page-head"><div class="eyebrow">ГЛАВНАЯ · КЛИЕНТЫ</div><h1>Клиенты</h1></section><section class="client-list">${state.clients.length?state.clients.map(clientCard).join(''):'<div class="empty-state">Клиентов пока нет</div>'}</section><button class="primary full" data-action="create-client" type="button">Создать клиента</button>`)}
function createClient(){const id=nextClientId();if(!id)return;state.clients.push({client_id:id,name:'',telegram_ids:[]});localStorage.setItem('cobook_clients',JSON.stringify(state.clients));state.selectedClientId=id;state.clientView='profile';render()}
function saveClient(id){const c=state.clients.find(x=>x.client_id===id);if(!c)return;const input=app.querySelector('[data-client-field="name"]');c.name=(input?.value||'').trim();localStorage.setItem('cobook_clients',JSON.stringify(state.clients));render()}
function addTelegram(id){const c=state.clients.find(x=>x.client_id===id);if(!c)return;const input=app.querySelector('[data-telegram-input]'),value=(input?.value||'').trim();if(!value)return;if(!Array.isArray(c.telegram_ids))c.telegram_ids=[];if(!c.telegram_ids.includes(value))c.telegram_ids.push(value);localStorage.setItem('cobook_clients',JSON.stringify(state.clients));render()}
function removeTelegram(id,index){const c=state.clients.find(x=>x.client_id===id);if(!c||!Array.isArray(c.telegram_ids))return;c.telegram_ids.splice(index,1);localStorage.setItem('cobook_clients',JSON.stringify(state.clients));render()}
window.CoBook.modules=window.CoBook.modules||{};window.CoBook.modules.clients=clients;
window.CoBook.clients={createClient,saveClient,addTelegram,removeTelegram};
