/* CoBook WALLETS — fixed payment types + user-defined wallets */
(function(){
 const KEY='cobook_wallets';
 const read=()=>{try{const v=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(v)?v:[]}catch(_){return[]}};
 const write=v=>localStorage.setItem(KEY,JSON.stringify(v));
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const newId=()=>crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random());
 const back=()=>CoBook.ui.button({label:'Назад',action:'navigate',variant:'secondary',attrs:'data-page="settings"',className:'section-back-button'});
 const primary=(label,action,attrs='')=>CoBook.ui.button({label,action,variant:'primary',attrs,className:'full'});
 function confirmDelete(wallet){if(!wallet)return '';return CoBook.ui.modal({kind:'wallet-delete',outerClassName:'confirm-modal',className:'confirm-modal-inner',content:`<div class="confirm-modal-eyebrow">УДАЛЕНИЕ КОШЕЛЬКА</div><h2 id="wallet-delete-title">Удалить «${esc(wallet.name)}»?</h2><p>Это действие удалит кошелёк и все данные, связанные с ним. Восстановить удалённые данные будет невозможно.</p><div class="confirm-modal-actions">${CoBook.ui.button({label:'Отмена',action:'wallet-delete-cancel',variant:'primary'})}${CoBook.ui.button({label:'Подтвердить удаление',action:'wallet-delete-confirm',variant:'danger'})}</div>`})}
 const listItem=(icon,title,subtitle,action='',index=null)=>CoBook.ui.listItem({icon,title,subtitle,action,actionLabel:action?'Удалить':'',actionAttrs:action&&index!==null?`data-wallet-index="${index}"`:'',itemClass:'wallet-list-item'});
 function home(){const wallets=read(),pending=Number.isInteger(state.walletDeleteIndex)?wallets[state.walletDeleteIndex]:null;return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ · КОШЕЛЬКИ</div><h1>Кошельки</h1><p>Системные способы оплаты и ваши собственные кошельки.</p></section><section class="wallet-section"><div class="wallet-section-title">Способы оплаты</div><div class="ui-list wallet-list">${listItem('₽','Наличный расчёт','Системный способ оплаты')}${listItem('▣','Безналичный расчёт','Системный способ оплаты')}</div></section><section class="wallet-section"><div class="wallet-section-title">Мои кошельки</div>${wallets.length?`<div class="ui-list wallet-list">${wallets.map((w,i)=>listItem('◉',w.name,'Пользовательский кошелёк','wallet-delete',i)).join('')}</div>`:'<div class="wallet-empty">Кошельков пока нет</div>'}</section>${primary('Добавить кошелёк','wallet-create')}${back()}${pending?confirmDelete(pending):''}`)}
 function editor(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ · КОШЕЛЁК</div><h1>Новый кошелёк</h1></section><section class="panel">${CoBook.ui.field({label:'Название кошелька',name:'wallet-name',placeholder:'Например, Сбербанк',attrs:'maxlength="60" autocomplete="off"'})}${primary('Сохранить','wallet-save')}</section>${back()}`)}
 function render(){return state.walletsView==='editor'?editor():home()}
 function refresh(){window.render()}
 function handle(action,e){if(action==='wallet-create'){state.walletsView='editor';state.walletDeleteIndex=null;refresh();return}if(action==='wallet-save'){const name=document.querySelector('[data-field="wallet-name"]')?.value.trim();if(!name)return;const wallets=read();wallets.push({id:newId(),name});write(wallets);state.walletsView='home';state.walletDeleteIndex=null;refresh();return}if(action==='wallet-delete'){const index=Number(e.dataset.walletIndex),wallets=read();if(!Number.isInteger(index)||index<0||index>=wallets.length)return;state.walletDeleteIndex=index;refresh();return}if(action==='wallet-delete-cancel'){state.walletDeleteIndex=null;refresh();return}if(action==='wallet-delete-confirm'){const index=state.walletDeleteIndex,wallets=read();if(!Number.isInteger(index)||index<0||index>=wallets.length){state.walletDeleteIndex=null;refresh();return}wallets.splice(index,1);write(wallets);state.walletDeleteIndex=null;refresh()}}
 CoBook.modules.wallets={render,handle,onEnter(){state.walletsView='home';state.walletDeleteIndex=null},onLeave(){}};
})();