function calendarDays(y,m){const labels=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];const first=new Date(y,m,1),offset=(first.getDay()+6)%7,total=42,a=labels.map(x=>`<div class="calendar-weekday">${x}</div>`);for(let i=0;i<total;i++){const day=i-offset+1,dt=new Date(y,m,day),inMonth=dt.getMonth()===m,k=dateKey(dt.getFullYear(),dt.getMonth(),dt.getDate()),r=state.rules[k],selected=state.selectedDates.has(k);a.push(`<button class="calendar-day${!inMonth?' outside':''}${inMonth&&selected?' selected':''}${inMonth&&r?' work':''}" data-action="calendar-date" data-date="${k}" type="button"><span>${dt.getDate()}</span></button>`)}return a.join('')}
function timeField(t,l,v){return `<button class="time-picker" data-action="open-time" data-time-type="${t}" type="button"><span>${l}</span><b>${v}</b></button>`}
function timetable(){const month=new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(new Date(state.year,state.month,1)),first=[...state.selectedDates][0],off=first&&state.rules[first];return shell(`<section class="page-head"><div class="eyebrow">ФОРМИРОВАНИЕ ГРАФИКА</div><h1>График</h1></section><section class="calendar-panel"><div class="period-row"><button class="period-arrow" data-action="year" data-direction="-1" type="button">‹</button><b>${state.year}</b><button class="period-arrow" data-action="year" data-direction="1" type="button">›</button></div><div class="period-row"><button class="period-arrow" data-action="month" data-direction="-1" type="button">‹</button><b>${month[0].toUpperCase()+month.slice(1)}</b><button class="period-arrow" data-action="month" data-direction="1" type="button">›</button></div><div class="calendar-grid">${calendarDays(state.year,state.month)}</div><section class="panel work-interval"><div class="panel-title">Рабочий интервал</div><div class="time-row">${timeField('start','Начало',state.startTime)}${timeField('end','Окончание',state.endTime)}</div><button class="primary full action-button${off?' schedule-action-off':''}" data-action="apply-schedule" type="button">${off?'Применить: Выходной день':'Применить: Рабочий день'}</button></section></section>`)}
function wheelItems(n,s){let x='';for(let i=0;i<n;i++){const v=String(i).padStart(2,'0');x+=`<button class="wheel-item${i===s?' selected':''}" data-wheel-value="${v}" type="button">${v}</button>`}return x}
function timeModal(t){const [h,m]=(t==='start'?state.startTime:state.endTime).split(':').map(Number);return `<div class="time-overlay" data-modal="time" data-time-type="${t}"><div class="time-sheet"><div class="time-sheet-head"><b>${t==='start'?'Начало':'Окончание'}</b><button class="time-done" data-modal-action="apply-time" type="button">Готово</button></div><div class="ios-wheel"><div class="wheel-column" data-wheel="hour">${wheelItems(24,h)}</div><span class="wheel-separator">:</span><div class="wheel-column" data-wheel="minute">${wheelItems(60,m)}</div><div class="wheel-highlight"></div></div></div></div>`}
function mountTimeModal(t){document.body.insertAdjacentHTML('beforeend',timeModal(t));const m=document.body.lastElementChild;m.querySelectorAll('.wheel-column').forEach(c=>{const s=c.querySelector('.selected');if(s)c.scrollTop=s.offsetTop-c.clientHeight/2+s.clientHeight/2;c.addEventListener('click',e=>{const x=e.target.closest('[data-wheel-value]');if(!x)return;c.querySelectorAll('.wheel-item').forEach(z=>z.classList.remove('selected'));x.classList.add('selected');c.scrollTo({top:x.offsetTop-c.clientHeight/2+x.clientHeight/2,behavior:'smooth'})})})}
function applyTime(m){const h=m.querySelector('[data-wheel="hour"] .selected')?.dataset.wheelValue,mi=m.querySelector('[data-wheel="minute"] .selected')?.dataset.wheelValue;if(!h||!mi)return;const v=`${h}:${mi}`;if(m.dataset.timeType==='start')state.startTime=v;else state.endTime=v;m.remove();render()}
function applySchedule(){const keys=[...state.selectedDates];if(!keys.length)return;const off=!!state.rules[keys[0]];if(!off){if(minutesValue(state.startTime)>=minutesValue(state.endTime))return;keys.forEach(k=>state.rules[k]={date:k,start:state.startTime,end:state.endTime,status:'working'})}else keys.forEach(k=>delete state.rules[k]);localStorage.setItem('cobook_work_rules',JSON.stringify(state.rules));state.selectedDates.clear();render()}
window.CoBook.modules=window.CoBook.modules||{};window.CoBook.modules.timetable=timetable;
window.CoBook.timetable={mountTimeModal,applyTime,applySchedule};
