(function(){
 let timeModal=null;
 let timeDraft={hour:'00',minute:'00'};
 function calendar(y,m){return CoBook.ui.calendarGrid({year:y,month:m,weekdayClass:'calendar-weekday',dayClass:'calendar-day',weekendClass:'weekend',outsideClass:'outside',renderDay:({day,key,weekend})=>{const r=state.rules[key],selected=state.selectedDates.has(key);return `<button class="calendar-day${weekend?' weekend':''}${selected?' selected':''}${r?' work':''}" data-action="calendar-date" data-date="${key}" type="button"><span>${day}</span>${r?`<small class="calendar-hours">${r.start}–${r.end}</small>`:''}</button>`}})}
 function timeModalMarkup(){if(!timeModal)return '';let hours='',mins='';for(let i=0;i<24;i++){const v=String(i).padStart(2,'0');hours+=`<button class="wheel-item${v===timeDraft.hour?' selected':''}" data-action="wheel-select" data-wheel="hour" data-wheel-value="${v}" type="button">${v}</button>`}for(let i=0;i<60;i++){const v=String(i).padStart(2,'0');mins+=`<button class="wheel-item${v===timeDraft.minute?' selected':''}" data-action="wheel-select" data-wheel="minute" data-wheel-value="${v}" type="button">${v}</button>`}return `<div class="time-overlay" data-modal="time" data-time-type="${timeModal}"><div class="time-sheet"><div class="time-sheet-head"><b>${timeModal==='start'?'Начало':'Окончание'}</b><button class="time-done" data-action="apply-time" type="button">Готово</button></div><div class="ios-wheel"><div class="wheel-column" data-wheel="hour">${hours}</div><span class="wheel-separator">:</span><div class="wheel-column" data-wheel="minute">${mins}</div><div class="wheel-highlight"></div></div></div></div>`}
 function render(){const month=new Intl.DateTimeFormat('ru-RU',{month:'long'}).format(new Date(state.year,state.month,1)),first=[...state.selectedDates][0],off=first&&state.rules[first];return shell(`<section class="page-head"><div class="eyebrow">ФОРМИРОВАНИЕ ГРАФИКА</div><h1>График</h1></section><section class="calendar-panel"><div class="period-row"><button class="period-arrow" data-action="year" data-direction="-1" type="button">‹</button><b>${state.year}</b><button class="period-arrow" data-action="year" data-direction="1" type="button">›</button></div><div class="period-row"><button class="period-arrow" data-action="month" data-direction="-1" type="button">‹</button><b>${month[0].toUpperCase()+month.slice(1)}</b><button class="period-arrow" data-action="month" data-direction="1" type="button">›</button></div><div class="calendar-grid">${calendar(state.year,state.month)}</div><section class="panel work-interval"><div class="panel-title">Рабочий интервал</div><div class="time-row"><button class="time-picker" data-action="open-time" data-time-type="start" type="button"><span>Начало</span><b>${state.startTime}</b></button><button class="time-picker" data-action="open-time" data-time-type="end" type="button"><span>Окончание</span><b>${state.endTime}</b></button></div><button class="primary full action-button${off?' schedule-action-off':''}" data-action="apply-schedule" type="button">${off?'Применить: Выходной день':'Применить: Рабочий день'}</button></section></section>${timeModalMarkup()}`)}
 function rerender(){window.render();if(timeModal){requestAnimationFrame(()=>{const root=document.querySelector('[data-modal="time"]');root?.querySelectorAll('.wheel-column').forEach(c=>{const s=c.querySelector('.selected');if(s)c.scrollTop=Math.max(0,s.offsetTop-c.clientHeight/2+s.clientHeight/2)})})}}
 function openTime(t){const current=t==='start'?state.startTime:state.endTime;const [h,m]=String(current).split(':');timeDraft={hour:String(h).padStart(2,'0'),minute:String(m).padStart(2,'0')};timeModal=t;rerender()}
 function handle(a,e,m){if(a==='wheel-select'){const wheel=e.dataset.wheel;if(wheel!=='hour'&&wheel!=='minute')return;timeDraft[wheel]=e.dataset.wheelValue;return rerender()}if(a==='apply-time'){if(!timeModal)return;const v=`${timeDraft.hour}:${timeDraft.minute}`;if(timeModal==='start')state.startTime=v;else state.endTime=v;timeModal=null;return rerender()}if(a==='calendar-date'){const k=e.dataset.date;if(state.selectedDates.size){const first=[...state.selectedDates][0];if(!!state.rules[first]!==!!state.rules[k])return}state.selectedDates.has(k)?state.selectedDates.delete(k):state.selectedDates.add(k);return rerender()}if(a==='open-time')return openTime(e.dataset.timeType);if(a==='year'){state.year+=Number(e.dataset.direction);return rerender()}if(a==='month'){state.month+=Number(e.dataset.direction);if(state.month<0){state.month=11;state.year--}if(state.month>11){state.month=0;state.year++}return rerender()}if(a==='apply-schedule'){const keys=[...state.selectedDates];if(!keys.length)return;const off=!!state.rules[keys[0]];if(!off){if(minutesValue(state.startTime)>=minutesValue(state.endTime))return;if(!state.rules)state.rules={};keys.forEach(k=>state.rules[k]={date:k,start:state.startTime,end:state.endTime,status:'working'})}else keys.forEach(k=>delete state.rules[k]);localStorage.setItem('cobook_work_rules',JSON.stringify(state.rules));state.selectedDates.clear();return rerender()}}
 CoBook.modules.timetable={render,handle};
})();
