(function(){
 const KEY='cobook_clients', CODE_KEY='cobook_client_codes', ACCOUNTS_KEY='cobook_telegram_accounts';
 const read=(k,f)=>{try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch(_){return f}}, write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const uid=()=>crypto.randomUUID?crypto.randomUUID():`c-${Date.now()}-${Math.random().toString(36).slice(2,8)}`;
 const normalizeCode=v=>{let s=String(v??'').trim().toUpperCase();if(/^\d{1,4}$/.test(s))s=s.padStart(4,'0');return /^[A-Z0-9]{4}$/.test(s)?s:null};
 function migrate(){let clients=read(KEY,[]);if(!Array.isArray(clients))clients=[];let reserved=read(CODE_KEY,[]);if(!Array.isArray(reserved))reserved=[];let accounts=read(ACCOUNTS_KEY,[]);if(!Array.isArray(accounts))accounts=[];
   clients=clients.map(c=>{const x={...c};if(!x.id)x.id=uid();if(!('code'in x))x.code=x.client_id?normalizeCode(x.client_id):null;if(!x.personal)x.personal={surname:'',gender:'',birthDate:''};if(!x.contacts)x.contacts={phones:[],email:''};if(!Array.isArray(x.contacts.phones))x.contacts.phones=x.contacts.phone?[String(x.contacts.phone)]:[];if(x.contacts.email===undefined)x.contacts.email='';if(!Array.isArray(x.telegram_accounts))x.telegram_accounts=[];if(!Array.isArray(x.tags))x.tags=[];if(!x.status)x.status='active';if(x.notes===undefined)x.notes='';if(!x.createdAt)x.createdAt=new Date().toISOString();if(!x.programs)x.programs={bonus:'',referral:'',other:''};if(!x.history)x.history={visits:0,totalSpent:0,lastVisit:null};if(!Array.isArray(x.codeHistory))x.codeHistory=[];if(x.code&&!reserved.includes(x.code))reserved.push(x.code);return x});
   clients.forEach(c=>c.telegram_accounts.forEach(a=>{if(!a.accountId)a.accountId=uid();let existing=accounts.find(x=>x.accountId===a.accountId);if(!existing)accounts.push({accountId:a.accountId,handle:a.handle,clientId:c.id,links:[{clientId:c.id,from:c.createdAt,to:null}]});else if(existing.clientId!==c.id)existing.clientId=c.id}));
   write(KEY,clients);write(CODE_KEY,reserved);write(ACCOUNTS_KEY,accounts);return clients;
 }
 const clients=()=>migrate(), saveClients=v=>write(KEY,v), saveAccount=a=>{const all=read(ACCOUNTS_KEY,[]),i=all.findIndex(x=>x.accountId===a.accountId);if(i<0)all.push(a);else all[i]=a;write(ACCOUNTS_KEY,all)}, accountById=id=>read(ACCOUNTS_KEY,[]).find(a=>a.accountId===id)||null;
 function codeUsed(code,exceptId){return read(CODE_KEY,[]).includes(code)||clients().some(c=>String(c.id)!==String(exceptId)&&c.code===code)}
 function list(){const a=clients();return shell(`<section class="page-head"><div class="eyebrow">ГЛАВНАЯ · КЛИЕНТЫ</div><h1>Клиенты</h1></section><section class="client-list">${a.length?a.map(c=>{const phone=c.contacts.phones[0]||'Телефон не указан';return `<button class="client-card" data-action="open-client" data-client-id="${esc(c.id)}" type="button"><span class="client-card-code">${esc(c.code||'—')}</span><span class="client-card-main"><b>${esc(c.name||'Без имени')}</b><small>${esc(phone)}</small></span><span class="client-card-arrow">›</span></button>`}).join(''):'<div class="empty-state">Клиентов пока нет</div>'}</section><button class="primary full" data-action="create-client" type="button">Создать клиента</button>`,false)}
 function profile(c){return shell(`<section class="page-head"><button class="back-button" data-action="maine-back-clients" type="button">‹ Клиенты</button><div class="eyebrow">КЛИЕНТ</div><h1>${esc(c.name||'Новый клиент')}</h1></section><section class="client-profile">${state.clientNotice?`<div class="client-notice">${esc(state.clientNotice)}</div>`:''}
 <div class="client-section"><div class="client-section-title">Идентификация</div><div class="client-grid"><label class="client-field"><span>Имя</span><input data-client-field="name" value="${esc(c.name||'')}"></label><label class="client-field"><span>Код</span><input data-client-code-input maxlength="4" inputmode="text" placeholder="0001" value="${esc(c.code||'')}"></label></div></div>
 <div class="client-section"><div class="client-section-title">Личные данные</div><div class="client-grid"><label class="client-field"><span>Фамилия</span><input data-client-field="surname" value="${esc(c.personal.surname||'')}"></label><label class="client-field"><span>Пол</span><select data-client-field="gender"><option value="" ${!c.personal.gender?'selected':''}>Не указан</option><option value="female" ${c.personal.gender==='female'?'selected':''}>Женский</option><option value="male" ${c.personal.gender==='male'?'selected':''}>Мужской</option></select></label><label class="client-field"><span>Дата рождения</span><input data-client-field="birthDate" type="date" value="${esc(c.personal.birthDate||'')}"></label></div></div>
 <div class="client-section"><div class="client-section-title">Контакты</div><label class="client-field"><span>Телефон</span><input data-phone-primary type="tel" placeholder="+7 ..." value="${esc(c.contacts.phones[0]||'')}"></label><div class="client-subtitle client-subtitle-spaced">Дополнительные телефоны</div>${c.contacts.phones.slice(1).map((p,i)=>`<div class="contact-row"><span>${esc(p)}</span><button class="secondary contact-remove" data-action="remove-phone" data-client-id="${esc(c.id)}" data-phone-index="${i+1}" type="button">Удалить</button></div>`).join('')}<div class="telegram-add"><input data-phone-input placeholder="+7 ..."><button class="secondary" data-action="add-phone" data-client-id="${esc(c.id)}" type="button">Добавить</button></div><div class="client-subtitle client-subtitle-spaced">Telegram</div>${c.telegram_accounts.length?c.telegram_accounts.map(a=>`<div class="telegram-row"><span>${esc(a.handle||'Telegram аккаунт')}</span><button class="secondary telegram-toggle" data-action="detach-telegram" data-client-id="${esc(c.id)}" data-account-id="${esc(a.accountId)}" type="button">Отвязать</button></div>`).join(''):'<div class="client-muted">Telegram не указан</div>'}<div class="telegram-add"><input data-telegram-input placeholder="@username"><button class="secondary" data-action="attach-telegram" data-client-id="${esc(c.id)}" type="button">Добавить</button></div><label class="client-field client-email-field"><span>Email</span><input data-client-field="email" value="${esc(c.contacts.email||'')}"></label></div>
 <div class="client-section"><div class="client-section-title">Программы</div><div class="client-grid"><label class="client-field"><span>Бонусная</span><input data-program="bonus" value="${esc(c.programs.bonus||'')}"></label><label class="client-field"><span>Реферальная</span><input data-program="referral" value="${esc(c.programs.referral||'')}"></label><label class="client-field"><span>Другие</span><input data-program="other" value="${esc(c.programs.other||'')}"></label></div></div>
 <div class="client-section"><div class="client-section-title">Клиентские данные</div><label class="client-field"><span>Дата создания профиля</span><input value="${esc(new Date(c.createdAt).toLocaleDateString('ru-RU'))}" disabled></label><label class="client-field"><span>Статус</span><select data-client-field="status"><option value="active" ${c.status==='active'?'selected':''}>Активный</option><option value="inactive" ${c.status==='inactive'?'selected':''}>Неактивный</option></select></label><div class="client-tag-list"><span class="client-subtitle">Ярлыки</span><span class="client-muted">Ярлыки выбираются из настроек</span></div><label class="client-field"><span>Заметки</span><textarea data-client-notes>${esc(c.notes||'')}</textarea></label></div>
 <div class="client-section"><div class="client-section-title">История</div><div class="history-summary"><div><b>${Number(c.history?.visits||0)}</b><span>Визиты</span></div><div><b>${Number(c.history?.visits||0)}</b><span>Количество визитов</span></div><div><b>${Number(c.history?.totalSpent||0).toLocaleString('ru-RU')} ₽</b><span>Общая сумма</span></div></div></div><button class="primary full" data-action="save-client" data-client-id="${esc(c.id)}" type="button">Сохранить</button></section>`,false)}
 function render(){const a=clients();if(state.clientView==='profile'){const c=a.find(x=>String(x.id)===String(state.selectedClientId));if(c)return profile(c);state.clientView='list';state.selectedClientId=null}return list()}
 function create(){const a=clients(),c={id:uid(),code:null,name:'',personal:{surname:'',gender:'',birthDate:''},contacts:{phones:[],email:''},programs:{bonus:'',referral:'',other:''},status:'active',tags:[],notes:'',createdAt:new Date().toISOString(),telegram_accounts:[],history:{visits:0,totalSpent:0,lastVisit:null},codeHistory:[]};a.push(c);saveClients(a);state.selectedClientId=c.id;state.clientView='profile';return window.render()}
 function handle(action,e){const a=clients();if(action==='open-client'){state.selectedClientId=e.dataset.clientId;state.clientView='profile';state.clientNotice='';return window.render()}if(action==='maine-back-clients'){state.clientView='list';state.selectedClientId=null;state.maineView='main';return window.render()}if(action==='create-client')return create();const c=a.find(x=>String(x.id)===String(e.dataset.clientId));if(!c)return;
   if(action==='save-client'){const code=normalizeCode(app.querySelector('[data-client-code-input]')?.value);if(!code){state.clientNotice='Укажите код клиента: 4 цифры или 4 латинских символа.';return window.render()}if(codeUsed(code,c.id)){state.clientNotice='Этот код уже использован.';return window.render()}c.code=code;c.name=app.querySelector('[data-client-field="name"]')?.value.trim()||'';const primaryPhone=app.querySelector('[data-phone-primary]')?.value.trim()||'';const extraPhones=c.contacts.phones.slice(1);c.contacts.phones=primaryPhone?[primaryPhone,...extraPhones]:extraPhones;c.personal.surname=app.querySelector('[data-client-field="surname"]')?.value.trim()||'';c.personal.gender=app.querySelector('[data-client-field="gender"]')?.value||'';c.personal.birthDate=app.querySelector('[data-client-field="birthDate"]')?.value||'';c.contacts.email=app.querySelector('[data-client-field="email"]')?.value.trim()||'';c.status=app.querySelector('[data-client-field="status"]')?.value||'active';c.notes=app.querySelector('[data-client-notes]')?.value||'';c.programs={bonus:app.querySelector('[data-program="bonus"]')?.value.trim()||'',referral:app.querySelector('[data-program="referral"]')?.value.trim()||'',other:app.querySelector('[data-program="other"]')?.value.trim()||''};const reserved=read(CODE_KEY,[]);if(!reserved.includes(code))reserved.push(code);write(CODE_KEY,reserved);saveClients(a);state.clientNotice='';return window.render()}
   if(action==='add-phone'){const v=app.querySelector('[data-phone-input]')?.value.trim();if(!v)return;c.contacts.phones=Array.isArray(c.contacts.phones)?c.contacts.phones:[];if(!c.contacts.phones.includes(v))c.contacts.phones.push(v);saveClients(a);return window.render()}
   if(action==='remove-phone'){c.contacts.phones.splice(Number(e.dataset.phoneIndex),1);saveClients(a);return window.render()}
   if(action==='attach-telegram'){const h=app.querySelector('[data-telegram-input]')?.value.trim();if(!h)return;let all=read(ACCOUNTS_KEY,[]),acc=all.find(x=>x.handle===h);if(!acc){acc={accountId:uid(),handle:h,clientId:null,links:[]};all.push(acc)}if(acc.clientId&&acc.clientId!==c.id){state.clientNotice='Этот Telegram аккаунт уже привязан к другому клиенту.';return window.render()}acc.clientId=c.id;acc.links=Array.isArray(acc.links)?acc.links:[];acc.links.push({clientId:c.id,from:new Date().toISOString(),to:null});if(!c.telegram_accounts.some(x=>x.accountId===acc.accountId))c.telegram_accounts.push({accountId:acc.accountId,handle:acc.handle});write(ACCOUNTS_KEY,all);saveClients(a);return window.render()}
   if(action==='detach-telegram'){const acc=accountById(e.dataset.accountId);if(!acc)return;acc.links=Array.isArray(acc.links)?acc.links:[];const open=[...acc.links].reverse().find(x=>x.clientId===c.id&&!x.to);if(open)open.to=new Date().toISOString();acc.clientId=null;saveAccount(acc);c.telegram_accounts=c.telegram_accounts.filter(x=>x.accountId!==e.dataset.accountId);saveClients(a);return window.render()}
 }
 CoBook.maineClients={render,handle};
})();
