(function(){
 const PROFILE_KEY='cobook_profile';
 const WORK_KEY='cobook_profile_workplaces';
 const roles=['Парикмахер','Барбер','Колорист','Мастер по наращиванию волос','Мастер маникюра','Мастер педикюра','Нейл-мастер','Визажист','Бровист','Лэшмейкер','Косметолог','Эстетист','Мастер депиляции','Мастер шугаринга','Мастер перманентного макияжа','Массажист','Стилист / имиджмейкер','Тату-мастер','Другое'];
 const experiences=['До 1 года','1–3 года','3–5 лет','5–10 лет','10–20 лет','Более 20 лет'];
 const currencies=[['RUB','₽ Рубли'],['USD','$ Доллары США'],['EUR','€ Евро'],['GBP','£ Фунты стерлингов']];
 const linkTypes=['Instagram','VK','YouTube','TikTok','Сайт','Другое'];
 let tab='personal'; let editingWorkId=null; let linkTarget=null;
 function resetView(){tab='personal';editingWorkId=null;linkTarget=null;document.querySelector('.profile-modal-backdrop')?.remove()}
 function profile(){return readStorage(PROFILE_KEY,{photo:'',name:'',phone:'',about:'',links:[],role:'',experience:'',professionAbout:''})}
 function workplaces(){const list=readStorage(WORK_KEY,[]);return Array.isArray(list)?list:[]}
 function saveProfile(p){localStorage.setItem(PROFILE_KEY,JSON.stringify(p))}
 function saveWorkplaces(list){localStorage.setItem(WORK_KEY,JSON.stringify(list))}
 function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
 function opt(list,value,empty){return `<option value="">${empty}</option>`+list.map(x=>{const val=Array.isArray(x)?x[0]:x,label=Array.isArray(x)?x[1]:x;return `<option value="${esc(val)}" ${value===val?'selected':''}>${esc(label)}</option>`}).join('')}
 function telegramLink(){try{const u=window.Telegram&&Telegram.WebApp&&Telegram.WebApp.initDataUnsafe&&Telegram.WebApp.initDataUnsafe.user;if(!u)return null;return {type:'Telegram',url:u.username?'https://t.me/'+u.username:'tg://user?id='+u.id}}catch(e){return null}}
 function ensureTelegram(p){const tg=telegramLink();if(tg&&!Array.isArray(p.links))p.links=[];if(tg&&!p.links.some(x=>x.type==='Telegram'))p.links=[tg,...p.links];return p}
 function tabs(){return `<div class="profile-tabs" role="tablist"><button type="button" class="profile-tab ${tab==='personal'?'is-active':''}" data-profile-action="tab" data-tab="personal">Личные</button><button type="button" class="profile-tab ${tab==='profession'?'is-active':''}" data-profile-action="tab" data-tab="profession">Профессия</button><button type="button" class="profile-tab ${tab==='work'?'is-active':''}" data-profile-action="tab" data-tab="work">Работа</button></div>`}
 function linkList(p){const links=Array.isArray(p.links)?p.links:[];return `<div class="profile-subsection"><div class="profile-row-title">Ссылки</div><div class="profile-link-list">${links.length?links.map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span>${l.type==='Telegram'?'<em>авто</em>':`<button type="button" class="profile-mini-btn" data-profile-action="delete-link" data-index="${i}">×</button>`}</div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-profile-action="add-link">+ Добавить ссылку</button></div>`}
 function personal(){const p=ensureTelegram(profile());return `<form class="profile-form" data-profile-form><section class="profile-card"><div class="profile-card-title">Личные</div><div class="profile-photo-line"><div class="profile-avatar">${p.photo?`<img src="${p.photo}" alt="Фото профиля">`:'<span>Фото</span>'}</div><div><b>Фото профиля</b><small>Основное фото пользователя</small><input type="file" accept="image/*" data-profile-photo></div></div><label class="profile-field"><span>Имя *</span><input name="name" required type="text" value="${esc(p.name)}" placeholder="Ваше имя" autocomplete="name"></label><label class="profile-field"><span>Телефон</span><input name="phone" type="tel" value="${esc(p.phone)}" placeholder="Номер телефона" autocomplete="tel"></label><label class="profile-field"><span>О себе</span><textarea name="about" rows="4" placeholder="Коротко о себе">${esc(p.about)}</textarea></label>${linkList(p)}</section><button class="primary profile-save" type="submit">Сохранить</button></form>`}
 function profession(){const p=profile();return `<form class="profile-form" data-profile-form><section class="profile-card"><div class="profile-card-title">Профессия</div><label class="profile-field"><span>Профессия</span><select name="role">${opt(roles,p.role,'Выберите профессию')}</select></label><label class="profile-field"><span>Опыт работы</span><select name="experience">${opt(experiences,p.experience,'Выберите опыт')}</select></label><label class="profile-field"><span>О профессии</span><textarea name="professionAbout" rows="5" placeholder="Расскажите о своей специализации и опыте">${esc(p.professionAbout)}</textarea></label></section><button class="primary profile-save" type="submit">Сохранить</button></form>`}
 function workList(){const list=workplaces();return `<section class="profile-card"><div class="profile-card-title">Работа</div><div class="work-list">${list.length?list.map(w=>`<article class="work-card"><div class="work-card-main"><b>${esc(w.name||'Место работы')}</b><span>${esc(w.city||'Город не указан')}${w.address?' · '+esc(w.address):''}</span></div><div class="work-card-meta">${esc(w.currencyLabel||'Валюта не указана')} · ${esc(w.schedule||'График не указан')}</div><div class="work-card-actions"><button type="button" class="profile-secondary-btn" data-profile-action="work-edit" data-id="${esc(w.id)}">Открыть</button><button type="button" class="profile-mini-btn" data-profile-action="work-delete" data-id="${esc(w.id)}">Удалить</button></div></article>`).join(''):'<div class="profile-empty">Мест работы пока нет.</div>'}</div><button type="button" class="primary" data-profile-action="work-add">+ Добавить место работы</button></section>`}
 function workForm(w){w=w||{id:'',name:'',city:'',address:'',phone:'',schedule:'',currency:'RUB',currencyLabel:'₽ Рубли',links:[],photos:[],about:''};return `<form class="profile-form" data-work-form data-id="${esc(w.id)}"><section class="profile-card"><div class="profile-card-title">${w.id?'Место работы':'Новое место работы'}</div><label class="profile-field"><span>Название</span><input name="name" required type="text" value="${esc(w.name)}" placeholder="Например, Салон Ромашка"></label><label class="profile-field"><span>Город</span><input name="city" type="text" value="${esc(w.city)}" placeholder="Город"></label><label class="profile-field"><span>Адрес</span><input name="address" type="text" value="${esc(w.address)}" placeholder="Адрес"></label><label class="profile-field"><span>Рабочий телефон</span><input name="phone" type="tel" value="${esc(w.phone)}" placeholder="Телефон"></label><label class="profile-field"><span>График работы</span><input name="schedule" type="text" value="${esc(w.schedule)}" placeholder="Например, Пн–Пт 10:00–20:00"></label><label class="profile-field"><span>Валюта</span><select name="currency">${opt(currencies,w.currency,'Выберите валюту')}</select></label><div class="profile-subsection"><div class="profile-row-title">Рабочие ссылки</div><div class="profile-link-list">${(w.links||[]).length?(w.links||[]).map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span><button type="button" class="profile-mini-btn" data-profile-action="work-link-delete" data-index="${i}">×</button></div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-profile-action="work-add-link">+ Добавить ссылку</button></div><div class="profile-subsection"><div class="profile-row-title">Фото рабочего пространства</div><div class="work-photo-grid">${(w.photos||[]).map((src,i)=>`<div class="work-photo"><img src="${src}" alt="Фото рабочего пространства"><button type="button" data-profile-action="work-photo-delete" data-index="${i}">×</button></div>`).join('')}<label class="work-photo-add"><input type="file" accept="image/*" multiple data-work-photo>+ Добавить фото</label></div><small class="profile-hint">Можно добавить до 3 фото.</small></div><label class="profile-field"><span>О рабочем пространстве</span><textarea name="about" rows="5" placeholder="Расскажите о месте работы">${esc(w.about)}</textarea></label></section><div class="profile-form-actions"><button type="button" class="profile-secondary-btn" data-profile-action="work-cancel">Отмена</button><button type="submit" class="primary">Сохранить место</button></div></form>`}
 function render(){let content=tab==='personal'?personal():tab==='profession'?profession():(editingWorkId!==null?workForm(editingWorkId?workplaces().find(x=>x.id===editingWorkId):null):workList());return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Профиль</h1><p>Один профиль мастера — личные данные, профессия и места работы.</p></section>${tabs()}${content}<div class="section-back-wrap"><button class="section-back-button" data-action="navigate" data-page="settings" type="button">Назад</button></div>`)}
 function readForm(form){return Object.fromEntries(new FormData(form).entries())}
 function openLinkModal(target){linkTarget=target;const title=target.workId?'Рабочая ссылка':'Ссылка';const options=linkTypes.map(x=>`<option>${x}</option>`).join('');const wrap=document.createElement('div');wrap.className='profile-modal-backdrop';wrap.innerHTML=`<div class="profile-modal" role="dialog" aria-modal="true"><div class="profile-modal-title">${title}</div><form data-profile-link-form><label class="profile-field"><span>Тип ссылки</span><select name="type">${options}</select></label><label class="profile-field"><span>Ссылка</span><input name="url" type="url" required placeholder="https://..."></label><div class="profile-form-actions"><button type="button" class="profile-secondary-btn" data-profile-action="modal-close">Отмена</button><button type="submit" class="primary">Добавить ссылку</button></div></form></div>`;document.body.appendChild(wrap);setTimeout(()=>wrap.querySelector('input')?.focus(),0)}
 function closeModal(){document.querySelector('.profile-modal-backdrop')?.remove();linkTarget=null}
 function handle(action,e){if(action==='tab'){tab=e.dataset.tab;editingWorkId=null;render();return}if(action==='add-link'){openLinkModal({workId:null});return}if(action==='delete-link'){const p=profile();p.links=(p.links||[]).filter((_,i)=>i!==Number(e.dataset.index));saveProfile(p);render();return}if(action==='work-add'){editingWorkId='__new__';render();return}if(action==='work-edit'){editingWorkId=e.dataset.id;render();return}if(action==='work-delete'){saveWorkplaces(workplaces().filter(w=>w.id!==e.dataset.id));render();return}if(action==='work-cancel'){editingWorkId=null;render();return}if(action==='work-add-link'){const form=document.querySelector('[data-work-form]');if(!form)return;openLinkModal({workId:form.dataset.id});return}if(action==='work-link-delete'){const form=document.querySelector('[data-work-form]');const w=workplaces().find(x=>x.id===form?.dataset.id);if(!w)return;w.links=(w.links||[]).filter((_,i)=>i!==Number(e.dataset.index));saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render();return}if(action==='work-photo-delete'){const form=document.querySelector('[data-work-form]');const w=workplaces().find(x=>x.id===form?.dataset.id);if(!w)return;w.photos=(w.photos||[]).filter((_,i)=>i!==Number(e.dataset.index));saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render();return}if(action==='modal-close'){closeModal();return}if(action==='profile-save'){const form=e.closest('[data-profile-form]');if(!form)return;const p=profile(),data=readForm(form);Object.assign(p,data);saveProfile(p);render();return}if(action==='work-save'){const form=e.closest('[data-work-form]');if(!form)return;const data=readForm(form),list=workplaces(),id=form.dataset.id&&form.dataset.id!=='__new__'?form.dataset.id:((window.crypto&&crypto.randomUUID)?crypto.randomUUID():Date.now().toString());const old=list.find(w=>w.id===id)||{};const w=Object.assign({id,links:[],photos:[]},old,data);w.currencyLabel=(currencies.find(x=>x[0]===w.currency)||['',''])[1];saveWorkplaces(old.id?list.map(x=>x.id===id?w:x):[...list,w]);editingWorkId=null;render();return}}
 document.addEventListener('click',e=>{const b=e.target.closest('[data-profile-action]');if(!b)return;e.preventDefault();e.stopPropagation();handle(b.dataset.profileAction,b)});
 document.addEventListener('submit',e=>{const lf=e.target.closest('[data-profile-link-form]');if(lf){e.preventDefault();const data=readForm(lf);if(linkTarget?.workId){const list=workplaces(),w=list.find(x=>x.id===linkTarget.workId);if(w){w.links=w.links||[];w.links.push({type:data.type,url:data.url});saveWorkplaces(list)}}else{const p=profile();p.links=Array.isArray(p.links)?p.links:[];p.links.push({type:data.type,url:data.url});saveProfile(p)}closeModal();render();return}const f=e.target.closest('[data-work-form]');if(f){e.preventDefault();handle('work-save',f);return}const p=e.target.closest('[data-profile-form]');if(p){e.preventDefault();handle('profile-save',p)}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-profile-photo]')){const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{const p=profile();p.photo=r.result;saveProfile(p);render()};r.readAsDataURL(file)}if(e.target.matches('[data-work-photo]')){const form=e.target.closest('[data-work-form]'),w=workplaces().find(x=>x.id===form?.dataset.id);if(!w)return;const files=[...(e.target.files||[])];const remaining=3-(w.photos||[]).length;files.slice(0,remaining).forEach(file=>{const r=new FileReader();r.onload=()=>{w.photos=[...(w.photos||[]),r.result];saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render()};r.readAsDataURL(file)})}});
 CoBook.modules.profile={render,handle,onEnter:resetView,onLeave:resetView};
})();
