(function(){
 const PROFILE_KEY='cobook_profile';
 const WORK_KEY='cobook_profile_workplaces';
 const TABS=['personal','profession','work'];
 const roles=['Парикмахер','Барбер','Колорист','Мастер по наращиванию волос','Мастер маникюра','Мастер педикюра','Нейл-мастер','Визажист','Бровист','Лэшмейкер','Косметолог','Эстетист','Мастер депиляции','Мастер шугаринга','Мастер перманентного макияжа','Массажист','Стилист / имиджмейкер','Тату-мастер','Другое'];
 const experiences=['До 1 года','1–3 года','3–5 лет','5–10 лет','10–20 лет','Более 20 лет'];
 const currencies=[['RUB','₽ Рубли'],['USD','$ Доллары США'],['EUR','€ Евро'],['GBP','£ Фунты стерлингов']];
 let tab='personal';
 let editingWorkId=null;
 function profile(){return readStorage(PROFILE_KEY,{photo:'',name:'',phone:'',about:'',links:[] ,role:'',experience:'',professionAbout:''});}
 function workplaces(){const list=readStorage(WORK_KEY,[]);return Array.isArray(list)?list:[]}
 function saveProfile(data){localStorage.setItem(PROFILE_KEY,JSON.stringify(data))}
 function saveWorkplaces(list){localStorage.setItem(WORK_KEY,JSON.stringify(list))}
 function telegramLink(){try{const u=window.Telegram&&Telegram.WebApp&&Telegram.WebApp.initDataUnsafe&&Telegram.WebApp.initDataUnsafe.user;if(!u)return null;if(u.username)return {type:'Telegram',url:'https://t.me/'+u.username};return {type:'Telegram',url:'tg://user?id='+u.id}}catch(e){return null}}
 function ensureTelegram(p){const tg=telegramLink();if(!tg)return p;if(!Array.isArray(p.links))p.links=[];if(!p.links.some(x=>x.type==='Telegram'))p.links=[tg,...p.links];return p}
 function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
 function opt(list,value,empty){return `<option value="">${empty}</option>`+list.map(x=>{const val=Array.isArray(x)?x[0]:x,label=Array.isArray(x)?x[1]:x;return `<option value="${esc(val)}" ${value===val?'selected':''}>${esc(label)}</option>`}).join('')}
 function tabs(){return `<div class="profile-tabs" role="tablist">${[['personal','Личные'],['profession','Профессия'],['work','Работа']].map(([id,label])=>`<button type="button" class="profile-tab ${tab===id?'is-active':''}" data-action="profile-tab" data-tab="${id}">${label}</button>`).join('')}</div>`}
 function linkList(p){const links=Array.isArray(p.links)?p.links:[];return `<div class="profile-subsection"><div class="profile-row-title">Ссылки</div><div class="profile-link-list">${links.length?links.map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span>${l.type==='Telegram'?'<em>авто</em>':`<button type="button" class="profile-mini-btn" data-action="profile-link-delete" data-index="${i}" aria-label="Удалить ссылку">×</button>`}</div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-action="profile-add-link">+ Добавить ссылку</button></div>`}
 function personal(){const p=ensureTelegram(profile());return `<form class="profile-form" data-profile-form><section class="profile-card"><div class="profile-card-title">Личные</div><div class="profile-photo-line"><div class="profile-avatar">${p.photo?`<img src="${p.photo}" alt="Фото профиля">`:'<span>Фото</span>'}</div><div><b>Фото профиля</b><small>Основное фото пользователя</small><input type="file" accept="image/*" data-profile-photo></div></div><label class="profile-field"><span>Имя *</span><input name="name" required type="text" value="${esc(p.name)}" placeholder="Ваше имя" autocomplete="name"></label><label class="profile-field"><span>Телефон</span><input name="phone" type="tel" value="${esc(p.phone)}" placeholder="Номер телефона" autocomplete="tel"></label><label class="profile-field"><span>О себе</span><textarea name="about" rows="4" placeholder="Коротко о себе">${esc(p.about)}</textarea></label>${linkList(p)}</section><button class="primary profile-save" type="submit">Сохранить</button></form>`}
 function profession(){const p=profile();return `<form class="profile-form" data-profile-form><section class="profile-card"><div class="profile-card-title">Профессия</div><label class="profile-field"><span>Профессия</span><select name="role">${opt(roles,p.role,'Выберите профессию')}</select></label><label class="profile-field"><span>Опыт работы</span><select name="experience">${opt(experiences,p.experience,'Выберите опыт')}</select></label><label class="profile-field"><span>О профессии</span><textarea name="professionAbout" rows="5" placeholder="Расскажите о своей специализации и опыте">${esc(p.professionAbout)}</textarea></label></section><button class="primary profile-save" type="submit">Сохранить</button></form>`}
 function workList(){const list=workplaces();return `<section class="profile-card"><div class="profile-card-title">Работа</div><div class="work-list">${list.length?list.map(w=>`<article class="work-card"><div class="work-card-main"><b>${esc(w.name||'Место работы')}</b><span>${esc(w.city||'Город не указан')}${w.address?' · '+esc(w.address):''}</span></div><div class="work-card-meta">${esc(w.currencyLabel||'Валюта не указана')} · ${esc(w.schedule||'График не указан')}</div><div class="work-card-actions"><button type="button" class="profile-secondary-btn" data-action="work-edit" data-id="${esc(w.id)}">Открыть</button><button type="button" class="profile-mini-btn" data-action="work-delete" data-id="${esc(w.id)}">Удалить</button></div></article>`).join(''):'<div class="profile-empty">Мест работы пока нет.</div>'}</div><button type="button" class="primary" data-action="work-add">+ Добавить место работы</button></section>`}
 function workForm(w){w=w||{id:'',name:'',city:'',address:'',phone:'',schedule:'',currency:'RUB',currencyLabel:'₽ Рубли',links:[],photos:[],about:''};return `<form class="profile-form" data-work-form data-id="${esc(w.id)}"><section class="profile-card"><div class="profile-card-title">${w.id?'Место работы':'Новое место работы'}</div><label class="profile-field"><span>Название</span><input name="name" required type="text" value="${esc(w.name)}" placeholder="Например, Салон Ромашка"></label><label class="profile-field"><span>Город</span><input name="city" type="text" value="${esc(w.city)}" placeholder="Город"></label><label class="profile-field"><span>Адрес</span><input name="address" type="text" value="${esc(w.address)}" placeholder="Адрес"></label><label class="profile-field"><span>Рабочий телефон</span><input name="phone" type="tel" value="${esc(w.phone)}" placeholder="Телефон"></label><label class="profile-field"><span>График работы</span><input name="schedule" type="text" value="${esc(w.schedule)}" placeholder="Например, Пн–Пт 10:00–20:00"></label><label class="profile-field"><span>Валюта</span><select name="currency">${opt(currencies,w.currency,'Выберите валюту')}</select></label><div class="profile-subsection"><div class="profile-row-title">Рабочие ссылки</div><div class="profile-link-list">${(w.links||[]).length?(w.links||[]).map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span><button type="button" class="profile-mini-btn" data-action="work-link-delete" data-index="${i}">×</button></div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-action="work-add-link">+ Добавить ссылку</button></div><div class="profile-subsection"><div class="profile-row-title">Фото рабочего пространства</div><div class="work-photo-grid">${(w.photos||[]).map((src,i)=>`<div class="work-photo"><img src="${src}" alt="Фото рабочего пространства"><button type="button" data-action="work-photo-delete" data-index="${i}">×</button></div>`).join('')}<label class="work-photo-add"><input type="file" accept="image/*" multiple data-work-photo>+ Добавить фото</label></div><small class="profile-hint">Можно добавить до 3 фото.</small></div><label class="profile-field"><span>О рабочем пространстве</span><textarea name="about" rows="5" placeholder="Расскажите о месте работы">${esc(w.about)}</textarea></label></section><div class="profile-form-actions"><button type="button" class="profile-secondary-btn" data-action="work-cancel">Отмена</button><button type="submit" class="primary">Сохранить место</button></div></form>`}
 function render(){let content;if(tab==='personal')content=personal();else if(tab==='profession')content=profession();else content=editingWorkId?workForm(workplaces().find(x=>x.id===editingWorkId)):workList();return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Профиль</h1><p>Один профиль мастера — личные данные, профессия и места работы.</p></section>${tabs()}${content}<div class="section-back-wrap"><button class="section-back-button" data-action="navigate" data-page="settings" type="button">Назад</button></div>`)}
 function readForm(form){return Object.fromEntries(new FormData(form).entries())}
 function handle(action,e){if(action==='profile-tab'){tab=e.dataset.tab;editingWorkId=null;render();return}if(action==='profile-add-link'){const type=prompt('Тип ссылки, например Instagram или VK');if(!type)return;const url=prompt('Ссылка');if(!url)return;const p=profile();p.links=Array.isArray(p.links)?p.links:[];p.links.push({type:type.trim(),url:url.trim()});saveProfile(p);render();return}if(action==='profile-link-delete'){const p=profile();p.links=(p.links||[]).filter((_,i)=>i!==Number(e.dataset.index));saveProfile(p);render();return}if(action==='work-add'){editingWorkId='';render();return}if(action==='work-edit'){editingWorkId=e.dataset.id;render();return}if(action==='work-delete'){saveWorkplaces(workplaces().filter(w=>w.id!==e.dataset.id));render();return}if(action==='work-cancel'){editingWorkId=null;render();return}if(action==='work-add-link'){const form=document.querySelector('[data-work-form]');const type=prompt('Тип рабочей ссылки, например Instagram');if(!type)return;const url=prompt('Ссылка');if(!url)return;const w=workplaces().find(x=>x.id===form.dataset.id);if(!w)return;w.links=w.links||[];w.links.push({type:type.trim(),url:url.trim()});saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render();return}if(action==='work-link-delete'){const form=document.querySelector('[data-work-form]');const w=workplaces().find(x=>x.id===form.dataset.id);if(!w)return;w.links=(w.links||[]).filter((_,i)=>i!==Number(e.dataset.index));saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render();return}if(action==='work-photo-delete'){const form=document.querySelector('[data-work-form]');const w=workplaces().find(x=>x.id===form.dataset.id);if(!w)return;w.photos=(w.photos||[]).filter((_,i)=>i!==Number(e.dataset.index));saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render();return}if(action==='profile-save'){const form=e.closest('[data-profile-form]');if(!form)return;const p=profile(),data=readForm(form);Object.assign(p,data);saveProfile(p);render();return}if(action==='work-save'){const form=e.closest('[data-work-form]');if(!form)return;const data=readForm(form),list=workplaces(),id=form.dataset.id||crypto.randomUUID();const old=list.find(w=>w.id===id)||{};const w=Object.assign({id,links:[],photos:[]},old,data);w.currencyLabel=(currencies.find(x=>x[0]===w.currency)||['',''])[1];saveWorkplaces(id&&old.id?list.map(x=>x.id===id?w:x):[...list,w]);editingWorkId=null;render();return}}
 document.addEventListener('submit',e=>{const f=e.target.closest('[data-work-form]');if(f){e.preventDefault();handle('work-save',f);return}const p=e.target.closest('[data-profile-form]');if(p){e.preventDefault();handle('profile-save',p)}});
 document.addEventListener('change',e=>{if(e.target.matches('[data-profile-photo]')){const file=e.target.files&&e.target.files[0];if(!file)return;const r=new FileReader();r.onload=()=>{const p=profile();p.photo=r.result;saveProfile(p);render()};r.readAsDataURL(file)}if(e.target.matches('[data-work-photo]')){const form=e.target.closest('[data-work-form]'),w=workplaces().find(x=>x.id===form.dataset.id);if(!w)return;const files=[...(e.target.files||[])];const remaining=3-(w.photos||[]).length;files.slice(0,remaining).forEach(file=>{const r=new FileReader();r.onload=()=>{w.photos=[...(w.photos||[]),r.result];saveWorkplaces(workplaces().map(x=>x.id===w.id?w:x));render()};r.readAsDataURL(file)})}});
 CoBook.modules.profile={render,handle};
})();
