(function(){
  let section='home';
  const professions=['Парикмахер','Колорист','Барбер','Визажист','Стилист','Мастер маникюра','Мастер педикюра','Бровист','Лэшмейкер','Косметолог','Массажист','Мастер по наращиванию волос','Мастер перманентного макияжа','Другое'];
  const experience=['Без опыта','До 1 года','1–3 года','3–5 лет','5–10 лет','10–15 лет','15–20 лет','Более 20 лет'];
  const currencies=['₽','€','$','₸','BYN','Другой'];
  function read(){try{return Object.assign({photo:'',name:'',phone:'',about:'',profession:'',experience:'',aboutProfession:'',workplaces:[]},JSON.parse(localStorage.getItem('cobook_profile')||'{}'))}catch(e){return {photo:'',name:'',phone:'',about:'',profession:'',experience:'',aboutProfession:'',workplaces:[]}}}
  function save(p){try{localStorage.setItem('cobook_profile',JSON.stringify(p))}catch(e){}}
  const back=()=>CoBook.ui.button({label:'Назад',action:'profile-back',variant:'secondary',className:'section-back-button'});
  const primary=(label,action,attrs='')=>CoBook.ui.button({label,action,variant:'primary',attrs});
  function render(){const content=section==='home'?home():section==='profession'?profession():section==='profileWork'?profileWork():personal();return shell(`<div class="profile-root">${content}</div>`)}
  function home(){return `<section class="page-head"><div class="eyebrow">НАСТРОЙКИ</div><h1>Профиль</h1><p>Профиль мастера</p></section>${CoBook.ui.folder({title:'Личные данные',subtitle:'Имя, телефон и информация о себе',action:'profile-personal',className:'profile-clean-folder'})}${CoBook.ui.folder({title:'Профессия',subtitle:'Профессия, опыт работы и информация о профессии',action:'profile-profession',className:'profile-clean-folder'})}${CoBook.ui.folder({title:'Работа',subtitle:'Места работы и рабочая информация',action:'profile-workplace',className:'profile-clean-folder'})}${back()}`}
  function personal(){return `<section class="page-head"><div class="eyebrow">ПРОФИЛЬ</div><h1>Личные данные</h1></section>${CoBook.profileSections.personal.render()}${back()}`}
  function profession(){const p=read();return `<section class="page-head"><div class="eyebrow">ПРОФИЛЬ</div><h1>Профессия</h1></section><div class="profile-clean-card"><form data-profession-form><label><span>Профессия</span><button type="button" class="profile-select" data-action="profile-profession-select"><span>${esc(p.profession||'Выберите профессию')}</span><b>⌄</b></button></label><label><span>Опыт работы</span><button type="button" class="profile-select" data-action="profile-experience-select"><span>${esc(p.experience||'Выберите стаж')}</span><b>⌄</b></button></label>${CoBook.ui.textarea({label:'О профессии',name:'aboutProfession',value:p.aboutProfession,placeholder:'Расскажите о своей профессии',className:'profile-control'})}<div class="profile-clean-actions">${primary('Сохранить','profile-profession-save')}</div></form></div>${back()}`}
  function profileWork(){const p=read(),ws=Array.isArray(p.workplaces)?p.workplaces:[];return `<section class="page-head"><div class="eyebrow">ПРОФИЛЬ</div><h1>Работа</h1><p>Места работы мастера</p></section>${ws.map((w,i)=>workCard(w,i)).join('')}${CoBook.ui.folder({title:'Добавить место работы',subtitle:'Создать отдельную карточку рабочего места',action:'profile-workplace-add',className:'profile-clean-folder'})}${ws.length?'':`<div class="profile-clean-muted profile-work-empty">Можно добавить несколько мест работы, в том числе в разных городах.</div>`}${back()}`}
  function workCard(w,i){return `<div class="profile-clean-card profile-work-card"><form data-workplace-form data-index="${i}"><div class="profile-work-card-title"><b>Место работы ${i+1}</b>${CoBook.ui.button({label:'Удалить',action:'profile-workplace-remove',variant:'danger',attrs:`data-index="${i}"`,className:'profile-work-remove'})}</div>${CoBook.ui.field({label:'Название',name:'name',value:w.name,placeholder:'Название места работы',className:'profile-control'})}${CoBook.ui.field({label:'Город',name:'city',value:w.city,placeholder:'Город',className:'profile-control'})}${CoBook.ui.field({label:'Адрес',name:'address',value:w.address,placeholder:'Адрес',className:'profile-control'})}${CoBook.ui.field({label:'Рабочий телефон',name:'phone',value:w.phone,placeholder:'Телефон',className:'profile-control'})}<label><span>Валюта</span><button type="button" class="profile-select" data-action="profile-workplace-currency-select" data-index="${i}"><span>${esc(w.currency||'Выберите валюту')}</span><b>⌄</b></button></label>${CoBook.ui.field({label:'График работы',name:'schedule',value:w.schedule,placeholder:'Например, Пн–Пт 10:00–20:00',className:'profile-control'})}${CoBook.ui.field({label:'Рабочие ссылки',name:'links',value:w.links,placeholder:'Ссылка на сайт или соцсети',className:'profile-control'})}${CoBook.ui.textarea({label:'О рабочем пространстве',name:'about',value:w.about,placeholder:'Расскажите о рабочем пространстве',className:'profile-control'})}<div class="profile-clean-actions">${primary('Сохранить','profile-workplace-save',`data-index="${i}"`)}</div></form></div>`}
  function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;')}
  function modal(title,items,action,index){return CoBook.ui.modal({kind:'profile-choice',outerClassName:'profile-choice',className:'profile-choice-inner',content:`<h2>${esc(title)}</h2>${items.map(x=>CoBook.ui.button({label:x,action,variant:'secondary',attrs:`data-value="${esc(x)}"${index!==undefined?` data-index="${index}"`:''}`})).join('')}${CoBook.ui.button({label:'Отмена',action:'modal-close',variant:'secondary'})}`})}
  function refresh(){window.render()}
  function reset(){section='home'}
  function handle(action,e){if(action==='profile-personal-save')return CoBook.profileSections.personal.handle(action,e);if(action==='profile-personal'){section='personal';return refresh()}if(action==='profile-profession'){section='profession';return refresh()}if(action==='profile-workplace'){section='profileWork';return refresh()}if(action==='profile-profession-select')return CoBook.ui.mountOverlay(modal('Профессия',professions,'profile-profession-choice'));if(action==='profile-experience-select')return CoBook.ui.mountOverlay(modal('Опыт работы',experience,'profile-experience-choice'));if(action==='profile-profession-choice'){const p=read();p.profession=e.dataset.value;save(p);e.closest('[data-modal]')?.remove();return refresh()}if(action==='profile-experience-choice'){const p=read();p.experience=e.dataset.value;save(p);e.closest('[data-modal]')?.remove();return refresh()}if(action==='profile-workplace-currency-select')return CoBook.ui.mountOverlay(modal('Валюта',currencies,'profile-workplace-currency-choice',e.dataset.index));if(action==='profile-workplace-currency-choice'){const p=read(),i=+e.dataset.index;p.workplaces=Array.isArray(p.workplaces)?p.workplaces:[];if(p.workplaces[i])p.workplaces[i].currency=e.dataset.value;save(p);e.closest('[data-modal]')?.remove();return refresh()}if(action==='profile-workplace-add'){const p=read();p.workplaces=Array.isArray(p.workplaces)?p.workplaces:[];p.workplaces.push({name:'',city:'',address:'',phone:'',currency:'',schedule:'',links:'',about:''});save(p);return refresh()}if(action==='profile-workplace-remove'){const p=read();p.workplaces=Array.isArray(p.workplaces)?p.workplaces:[];p.workplaces.splice(+e.dataset.index,1);save(p);return refresh()}if(action==='profile-profession-save'){const form=e.closest('[data-profession-form]');if(!form)return;const p=read();p.aboutProfession=String(new FormData(form).get('aboutProfession')||'');save(p);return refresh()}if(action==='profile-workplace-save'){const i=+e.dataset.index,form=e.closest('[data-workplace-form]'),p=read();p.workplaces=Array.isArray(p.workplaces)?p.workplaces:[];if(form&&p.workplaces[i]){const f=new FormData(form);p.workplaces[i]={...p.workplaces[i],name:String(f.get('name')||''),city:String(f.get('city')||''),address:String(f.get('address')||''),phone:String(f.get('phone')||''),schedule:String(f.get('schedule')||''),links:String(f.get('links')||''),about:String(f.get('about')||'')};save(p)}return refresh()}if(action==='profile-back'){if(section!=='home'){section='home';return refresh()}reset();return navigate('settings')}}
  CoBook.modules.profile={render,refresh,handle,onEnter:reset,onLeave:reset};
})();