(function(){
 const readStorage=(key,fallback)=>{try{const raw=localStorage.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch(e){try{localStorage.removeItem(key)}catch(_){}return fallback}};
 const today=new Date(); const dateKey=(y,m,d)=>`${y}-${m+1}-${d}`;
 const savedRules=readStorage('cobook_work_rules',{}), savedProcedures=readStorage('cobook_procedures',[{name:'Женская стрижка',duration:60,price:''},{name:'Мужская стрижка',duration:45,price:''},{name:'Детская стрижка',duration:45,price:''}]), savedProducts=readStorage('cobook_products',[{name:'Шампунь',price:''},{name:'Кондиционер',price:''},{name:'Краска для волос',duration:45,price:''}]), savedClients=readStorage('cobook_clients',[]);
 window.CoBook=window.CoBook||{}; CoBook.modules=CoBook.modules||{};
 window.state={page:'journal',settingsView:'home',year:today.getFullYear(),month:today.getMonth(),selectedDates:new Set(),startTime:'10:00',endTime:'20:00',rules:savedRules||{},journalDate:dateKey(today.getFullYear(),today.getMonth(),today.getDate()),journalMode:'day',serviceMode:'procedures',procedures:Array.isArray(savedProcedures)?savedProcedures:[],products:Array.isArray(savedProducts)?savedProducts:[],clients:Array.isArray(savedClients)?savedClients:[],activeClientId:null,maineView:'main',tagsView:'home',walletsView:'home'};
 const app=document.getElementById('app'); window.app=app; window.dateKey=dateKey;
 window.minutesValue=t=>{const [h,m]=String(t).split(':').map(Number);return h*60+m}; window.readStorage=readStorage;
 const navItems=[['maine','⌂','Главная'],['timetable','▦','График'],['journal','▤','Журнал'],['chat','◌','Чат'],['settings','⚙','Настройки']];
 window.nav=()=>`<nav class="bottom">${navItems.map(([p,i,l])=>`<button class="nav" data-action="navigate" data-page="${p}" type="button"><span class="nav-icon">${i}</span><span>${l}</span></button>`).join('')}</nav>`;
 window.shell=(content,plain=false)=>`<div class="shell">${plain?'':`<header class="topbar"><div class="brand">CoBook</div><div class="subtitle">Кабинет мастера</div></header>`}<main class="content">${content}</main>${nav()}</div>`;
 const moduleFor=p=>CoBook.modules[p];
 const settingsChildPages=new Set(['profile','service','work','documents','loyalty','tags','wallets']);
 const actionOwners=new Map([['clients-open','maine'],['client-new','maine'],['client-open','maine'],['client-save','maine'],['client-back','maine'],['maine-back','maine']]);
 const listContainers=['service-list','loyalty-list','work-list','wallet-list','tags-list','documents-list','client-list','loyalty-menu'];
 const listItems=['service-row','procedure-card','product-card','work-card','wallet-row','tags-row','document-card','client-row','loyalty-card','management-folder','profile-clean-folder'];
 const normalizeUI=()=>{
   document.querySelectorAll(listContainers.map(x=>'.'+x).join(',')).forEach(el=>el.classList.add('ui-list'));
   document.querySelectorAll(listItems.map(x=>'.'+x).join(',')).forEach(el=>el.classList.add('ui-list-item'));
   document.querySelectorAll('button:not(.nav)').forEach(el=>el.classList.add('ui-button'));
   document.querySelectorAll('input:not([type="file"]),select,textarea').forEach(el=>el.classList.add('ui-control'));
 };
 const escapeHtml=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
 const attrValue=v=>String(v??'').replace(/&/g,'&amp;').replace(/\"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;');
 window.CoBook.ui=window.CoBook.ui||{};
 CoBook.ui.listItem=({icon='',iconAttrs='',title='',subtitle='',action='',actionLabel='',actionClass='danger',actionAttrs='',contentClass='',itemClass=''})=>`<div class="ui-list-item ui-entity-row ${itemClass}">${icon?`<span class="ui-entity-icon" ${attrValue(iconAttrs)} aria-hidden="true">${icon}</span>`:''}<div class="ui-entity-content ${contentClass}"><div class="ui-entity-title">${escapeHtml(title)}</div>${subtitle?`<div class="ui-entity-subtitle">${escapeHtml(subtitle)}</div>`:''}</div>${action?`<button class="${actionClass}" data-action="${attrValue(action)}" ${attrValue(actionAttrs)} type="button">${escapeHtml(actionLabel)}</button>`:''}</div>`;
 window.navigate=page=>{
   const nextPage=String(page||'maine'),previousPage=state.page,previousModule=moduleFor(previousPage);
   if(previousModule&&typeof previousModule.onLeave==='function')previousModule.onLeave(nextPage);
   state.page=nextPage; state.settingsView=nextPage==='settings'?'home':(settingsChildPages.has(nextPage)?nextPage:'home'); if(nextPage!=='maine')state.maineView='main';
   const nextModule=moduleFor(nextPage); if(nextModule&&typeof nextModule.onEnter==='function')nextModule.onEnter(previousPage); render();
 };
 window.render=()=>{const mod=moduleFor(state.page)||CoBook.modules.maine;app.innerHTML=mod.render();normalizeUI();};
 window.dispatchAction=(action,e)=>{if(action==='navigate')return navigate(e.dataset.page);if(action==='modal-close')return e.closest('[data-modal]')?.remove();const owner=actionOwners.get(action),mod=moduleFor(owner||state.page);if(mod&&typeof mod.handle==='function')return mod.handle(action,e,e.closest('[data-modal]')||null)};
 const handleClick=e=>{const target=e.target&&e.target.nodeType===1?e.target:e.target?.parentElement,actionElement=target?.closest?.('[data-action]');if(!actionElement)return;dispatchAction(actionElement.dataset.action,actionElement)};
 document.addEventListener('click',handleClick,true);
 let normalizeQueued=false;
 const observer=new MutationObserver(()=>{if(normalizeQueued)return;normalizeQueued=true;queueMicrotask(()=>{normalizeQueued=false;normalizeUI()})});
 observer.observe(app,{subtree:true,childList:true});
 window.CoBook.core={moduleFor,normalizeUI};
})();
