(function(){
 const KEY='cobook_profile_workplaces'; const C=[['RUB','₽ Рубли'],['USD','$ Доллары США'],['EUR','€ Евро'],['GBP','£ Фунты стерлингов']]; const L=['Instagram','VK','YouTube','TikTok','Сайт','Другое'];
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');
 const read=()=>{const x=readStorage(KEY,[]);return Array.isArray(x)?x:[]}; const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
 const opt=(list,v,empty)=>`<option value="">${empty}</option>`+list.map(x=>{const a=Array.isArray(x)?x[0]:x,b=Array.isArray(x)?x[1]:x;return `<option value="${esc(a)}" ${v===a?'selected':''}>${esc(b)}</option>`}).join('');
 function list(){const a=read();return `<section class="profile-card"><div class="profile-card-title">Рабочие данные</div><div class="work-list">${a.length?a.map(w=>`<article class="work-card"><div class="work-card-main"><b>${esc(w.name||'Место работы')}</b><span>${esc(w.city||'Город не указан')}${w.address?' · '+esc(w.address):''}</span></div><div class="work-card-meta">${esc(w.currencyLabel||'Валюта не указана')} · ${esc(w.schedule||'График не указан')}</div><div class="work-card-actions"><button type="button" class="profile-secondary-btn" data-action="work-edit" data-id="${esc(w.id)}">Открыть</button><button type="button" class="profile-mini-btn" data-action="work-delete" data-id="${esc(w.id)}">Удалить</button></div></article>`).join(''):'<div class="profile-empty">Мест работы пока нет.</div>'}</div><button type="button" class="primary" data-action="work-add">+ Добавить место работы</button></section>`}
 function form(w){w=w||{id:'',name:'',city:'',address:'',phone:'',schedule:'',currency:'RUB',currencyLabel:'₽ Рубли',links:[],photos:[],about:''};return `<form class="profile-form" data-work-form data-id="${esc(w.id)}"><section class="profile-card"><div class="profile-card-title">${w.id?'Место работы':'Новое место работы'}</div><label class="profile-field"><span>Название</span><input name="name" required type="text" value="${esc(w.name)}" placeholder="Например, Салон Ромашка"></label><label class="profile-field"><span>Город</span><input name="city" type="text" value="${esc(w.city)}" placeholder="Город"></label><label class="profile-field"><span>Адрес</span><input name="address" type="text" value="${esc(w.address)}" placeholder="Адрес"></label><label class="profile-field"><span>Рабочий телефон</span><input name="phone" type="tel" value="${esc(w.phone)}" placeholder="Телефон"></label><label class="profile-field"><span>График работы</span><input name="schedule" type="text" value="${esc(w.schedule)}" placeholder="Например, Пн–Пт 10:00–20:00"></label><label class="profile-field"><span>Валюта</span><select name="currency">${opt(C,w.currency,'Выберите валюту')}</select></label><div class="profile-subsection"><div class="profile-row-title">Рабочие ссылки</div><div class="profile-link-list">${(w.links||[]).length?w.links.map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span><button type="button" class="profile-mini-btn" data-action="work-link-delete" data-index="${i}">×</button></div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-action="work-add-link">+ Добавить ссылку</button></div><div class="profile-subsection"><div class="profile-row-title">Фото рабочего пространства</div><div class="work-photo-grid">${(w.photos||[]).map((src,i)=>`<div class="work-photo"><img src="${src}" alt="Фото рабочего пространства"><button type="button" data-action="work-photo-delete" data-index="${i}">×</button></div>`).join('')}<label class="work-photo-add"><input type="file" accept="image/*" multiple data-work-photo>+ Добавить фото</label></div><small class="profile-hint">Можно добавить до 3 фото.</small></div><label class="profile-field"><span>О рабочем пространстве</span><textarea name="about" rows="5" placeholder="Расскажите о месте работы">${esc(w.about)}</textarea></label></section><div class="profile-form-actions"><button type="button" class="profile-secondary-btn" data-action="work-cancel">Назад</button><button type="submit" class="primary">Сохранить место</button></div></form>`}
 window.CoBook=window.CoBook||{};CoBook.profileSections=CoBook.profileSections||{};CoBook.profileSections.work={list,form,read,save,C,L};
})();
