(function(){
 const KEY='cobook_profile';
 const LINK_TYPES=['Instagram','VK','YouTube','TikTok','Сайт','Другое'];
 const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#39;');
 function read(){return readStorage(KEY,{photo:'',name:'',phone:'',about:'',links:[],role:'',experience:'',professionAbout:''})}
 function save(p){localStorage.setItem(KEY,JSON.stringify(p))}
 function telegram(){try{const u=window.Telegram?.WebApp?.initDataUnsafe?.user;if(!u)return null;return {type:'Telegram',url:u.username?'https://t.me/'+u.username:'tg://user?id='+u.id}}catch(e){return null}}
 function ensure(p){const t=telegram();if(t){p.links=Array.isArray(p.links)?p.links:[];if(!p.links.some(x=>x.type==='Telegram'))p.links=[t,...p.links]}return p}
 function links(p){const a=Array.isArray(p.links)?p.links:[];return `<div class="profile-subsection"><div class="profile-row-title">Ссылки</div><div class="profile-link-list">${a.length?a.map((l,i)=>`<div class="profile-link-item"><span><b>${esc(l.type||'Ссылка')}</b><small>${esc(l.url)}</small></span>${l.type==='Telegram'?'<em>авто</em>':`<button type="button" class="profile-mini-btn" data-profile-action="delete-link" data-index="${i}">×</button>`}</div>`).join(''):'<div class="profile-muted">Пока нет ссылок</div>'}</div><button type="button" class="profile-secondary-btn" data-profile-action="add-link">+ Добавить ссылку</button></div>`}
 function render(){const p=ensure(read());return `<form class="profile-form" data-profile-form><section class="profile-card"><div class="profile-card-title">Личные данные</div><div class="profile-photo-line"><div class="profile-avatar">${p.photo?`<img src="${p.photo}" alt="Фото профиля">`:'<span>Фото</span>'}</div><div><b>Фото профиля</b><small>Основное фото пользователя</small><input type="file" accept="image/*" data-profile-photo></div></div><label class="profile-field"><span>Имя *</span><input name="name" required type="text" value="${esc(p.name)}" placeholder="Ваше имя" autocomplete="name"></label><label class="profile-field"><span>Телефон</span><input name="phone" type="tel" value="${esc(p.phone)}" placeholder="Номер телефона" autocomplete="tel"></label><label class="profile-field"><span>О себе</span><textarea name="about" rows="4" placeholder="Коротко о себе">${esc(p.about)}</textarea></label>${links(p)}</section><button class="primary profile-save" type="submit">Сохранить</button></form>`}
 window.CoBook=window.CoBook||{};CoBook.profileSections=CoBook.profileSections||{};CoBook.profileSections.personal={render,read,save,LINK_TYPES,telegram,ensure};
})();
