const {chromium}=require('playwright');
const fs=require('fs');
const path=require('path');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const page=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1});
 const errors=[];
 page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));
 page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});
 const base=process.env.COBOOK_BASE_URL||'http://127.0.0.1:4173/';
 const click=async action=>{await page.locator(`[data-action="${action}"]`).first().click()};
 const expectText=async text=>{await page.getByText(text,{exact:true}).waitFor({state:'visible',timeout:5000})};
 await page.goto(base,{waitUntil:'networkidle'});
 await expectText('Главная');
 await click('clients-open');
 await expectText('Клиенты');
 await click('client-new');
 await expectText('Сохранить');
 await page.locator('[data-field="client-name"]').fill('Smoke Client');
 await click('client-save');
 await expectText('Smoke Client');
 await click('client-back');
 await click('maine-back');
 await click('navigate');
 // Navigation action needs an explicit page; use bottom navigation directly.
 await page.locator('[data-action="navigate"][data-page="settings"]').click();
 await expectText('Настройки');
 await page.locator('[data-action="navigate"][data-page="wallets"]').click();
 await expectText('Кошельки');
 await click('wallet-create');
 await page.locator('[data-field="wallet-name"]').fill('Smoke Wallet');
 await click('wallet-save');
 await expectText('Smoke Wallet');
 await page.locator('[data-action="navigate"][data-page="tags"]').click();
 await expectText('Ярлыки');
 await click('tag-create');
 await page.locator('[data-field="tag-name"]').fill('Smoke Tag');
 await click('tag-save');
 await expectText('Smoke Tag');
 await page.locator('[data-action="navigate"][data-page="service"]').click();
 await expectText('Сервис');
 await click('open-procedure');
 await page.locator('[data-modal="service"] [data-field="name"]').fill('Smoke Procedure');
 await click('save-service');
 await expectText('Smoke Procedure');
 await page.locator('[data-action="navigate"][data-page="work"]').click();
 await expectText('Рабочие материалы');
 await click('materials-new');
 await page.locator('[data-modal="work-material"] [data-field="name"]').fill('Smoke Material');
 await click('materials-save');
 await expectText('Smoke Material');
 await page.locator('[data-action="navigate"][data-page="documents"]').click();
 await expectText('Документы');
 await page.locator('[data-action="navigate"][data-page="profile"]').click();
 await expectText('Профиль');
 await page.locator('[data-action="profile-personal"]').click();
 await page.locator('[data-field="name"]').fill('Smoke Name');
 await click('profile-personal-save');
 await expectText('Личные данные');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log('CoBook browser smoke PASS');
 await browser.close();
})().catch(async e=>{console.error(e.stack||e);process.exitCode=1});
