(function(){
  window.CoBook=window.CoBook||{}; CoBook.modules=CoBook.modules||{};
  const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;');
  function normalize(p){if(!p.priceType){if(p.priceFrom||p.priceTo)p.priceType=p.priceTo?'range':'from';else if(p.price)p.priceType='exact';else p.priceType='exact'}if(p.priceFrom==null&&p.price)p.priceFrom=p.price;if(p.priceTo==null)p.priceTo='';return p}
  function workplaces(){try{const p=JSON.parse(localStorage.getItem('cobook_profile')||'{}');return Array.isArray(p.workplaces)?p.workplaces.map((w,i)=>({...w,id:w.id||`workplace-${i}`,name:w.name||`Место работы ${i+1}`})):[]}catch(e){return []}}
  function priceVariant(v={}){const type=v.priceType||'exact';return {workplaceId:v.workplaceId||'',priceType:type,priceFrom:v.priceFrom??v.price??'',priceTo:v.priceTo??''}}
  function procedureVariants(item){if(Array.isArray(item.prices)&&item.prices.length)return item.prices.map(priceVariant);return [priceVariant({workplaceId:item.workplaceId||'',priceType:item.priceType,priceFrom:item.priceFrom,priceTo:item.priceTo,price:item.price})]}
  const primary=(label,action,attrs='',className='full')=>CoBook.ui.button({label,action,variant:'primary',attrs,className});
  const secondary=(label,action,attrs='',className='full')=>CoBook.ui.button({label,action,variant:'secondary',attrs,className});
  const toggle=(label,action,attrs='',active=false)=>CoBook.ui.button({label,action,variant:'secondary',attrs,className:`price-mode-btn${active?' active':''}`});
  function render(){const procedures=state.serviceMode==='procedures',views=CoBook.serviceViews||{},view=procedures?(views.procedures?.render?views.procedures.render(state):''):(views.products?.render?views.products.render(state):'');return shell(`<section class="page-head service-head"><div class="eyebrow">НАСТРОЙКИ · СЕРВИС</div><h1>Сервис</h1></section><div class="service-tabs" role="tablist">${CoBook.ui.button({label:'Процедуры',action:'service-tab',variant:'secondary',attrs:`data-mode="procedures" role="tab" aria-selected="${procedures}"`,className:`service-tab ${procedures?'active':''}`})}${CoBook.ui.button({label:'Товары',action:'service-tab',variant:'secondary',attrs:`data-mode="products" role="tab" aria-selected="${!procedures}"`,className:`service-tab ${!procedures?'active':''}`})}</div><div class="service-view">${view}</div>${CoBook.ui.button({label:'Назад',action:'navigate',variant:'secondary',attrs:'data-page="settings"',className:'section-back-button'})}`)}
  function workplaceOptions(selected){const ws=workplaces();return [{value:'',label:'Без привязки к месту'},...ws.map(w=>({value:w.id,label:w.name}))]}
  function priceBlock(v,i){const type=v.priceType||'exact';return `<div class="procedure-price-variant" data-price-variant data-variant-index="${i}">${CoBook.ui.select({label:'Место работы',name:'workplace',value:v.workplaceId,options:workplaceOptions(v.workplaceId)})}<div class="price-mode-label">Цена</div><div class="price-mode" data-price-mode>${toggle('Цена','price-type','data-price-type="exact"',type==='exact')}${toggle('От','price-type','data-price-type="from"',type==='from')}${toggle('От–до','price-type','data-price-type="range"',type==='range')}</div><div class="price-fields ${type==='range'?'range':''}">${CoBook.ui.field({label:type==='exact'?'Цена':'Цена от',name:'price-from',value:v.priceFrom||'',attrs:'inputmode="decimal"'})}${CoBook.ui.field({label:'Цена до',name:'price-to',value:v.priceTo||'',attrs:'inputmode="decimal"',className:'price-to-field'})}</div>${i>0?CoBook.ui.button({label:'Удалить вариант цены',action:'remove-price-variant',variant:'danger',className:'full procedure-price-remove'}):''}</div>`}
  function modal(kind,index=null){const isProcedure=kind==='procedure',source=isProcedure?state.procedures:state.products,item=index===null?(isProcedure?{name:'',duration:60,prices:[priceVariant()]}:{name:'',price:'',image:''}):normalize({...source[index]}),meta=`data-kind="${isProcedure?'procedure':'product'}" data-index="${index===null?'':index}"`;if(isProcedure){const variants=procedureVariants(item);return CoBook.ui.modal({kind:'service',outerClassName:'service-overlay',className:'service-sheet procedure-editor',attrs:meta,content:`<div class="service-sheet-head"><b>${index===null?'Новая процедура':'Процедура'}</b>${CoBook.ui.button({label:'×',action:'modal-close',variant:'secondary',className:'service-close'})}</div>${CoBook.ui.field({label:'Наименование процедуры',name:'name',value:item.name,attrs:'autocomplete="off"'})}${CoBook.ui.field({label:'Время в работе',name:'duration',value:item.duration,type:'number',attrs:'min="1" inputmode="numeric"'})}<div class="procedure-prices" data-procedure-prices>${variants.map(priceBlock).join('')}</div>${secondary('+ Добавить место работы','add-price-variant')}${primary('Сохранить','save-service')}${CoBook.ui.button({label:'Назад',action:'modal-close',variant:'secondary',className:'section-back-button'})}`})}return CoBook.ui.modal({kind:'service',outerClassName:'service-overlay',className:'service-sheet product-editor',attrs:meta,content:`<div class="service-sheet-head"><b>${index===null?'Новый товар':'Товар'}</b>${CoBook.ui.button({label:'×',action:'modal-close',variant:'secondary',className:'service-close'})}</div><label class="product-upload" data-product-upload><span class="product-upload-preview">${item.image?`<img src="${item.image}" alt="">`:'+'}</span><span><b>Фото товара</b><small>Выбрать изображение</small></span><input type="file" accept="image/*" data-field="image-file"></label>${CoBook.ui.field({label:'Название товара',name:'name',value:item.name,attrs:'autocomplete="off"'})}${CoBook.ui.field({label:'Стоимость',name:'price',value:item.price||'',attrs:'inputmode="decimal"'})}${primary('Сохранить','save-service')}${CoBook.ui.button({label:'Назад',action:'modal-close',variant:'secondary',className:'section-back-button'})}`})}
  function save(modal){const name=modal.querySelector('[data-field="name"]')?.value.trim()||'',kind=modal.dataset.kind,index=modal.dataset.index===''?null:Number(modal.dataset.index);if(!name)return;if(kind==='procedure'){const duration=Math.max(1,Number(modal.querySelector('[data-field="duration"]')?.value)||60),prices=[...modal.querySelectorAll('[data-price-variant]')].map(v=>{const type=v.querySelector('[data-price-type].active')?.dataset.priceType||'exact';return {workplaceId:v.querySelector('[data-field="workplace"]')?.value||'',priceType:type,priceFrom:v.querySelector('[data-field="price-from"]')?.value.trim()||'',priceTo:type==='range'?(v.querySelector('[data-field="price-to"]')?.value.trim()||''):''}}).filter(v=>v.priceFrom||v.priceTo||v.workplaceId);const item={name,duration,prices:prices.length?prices:[priceVariant()]};if(index===null)state.procedures.push(item);else state.procedures[index]=item;localStorage.setItem('cobook_procedures',JSON.stringify(state.procedures))}else{const price=modal.querySelector('[data-field="price"]')?.value.trim()||'',old=index===null?{}:(state.products[index]||{}),file=modal.querySelector('[data-field="image-file"]'),image=file?.dataset.imageData||old.image||'',item={name,price,image};if(index===null)state.products.push(item);else state.products[index]=item;localStorage.setItem('cobook_products',JSON.stringify(state.products))}modal.remove();window.render()}
  function openOverlay(markup){return CoBook.ui.mountOverlay(markup)}
  function appendPriceVariant(wrap){const template=document.createElement('template');template.innerHTML=priceBlock(priceVariant(),wrap.querySelectorAll('[data-price-variant]').length);wrap.append(template.content.cloneNode(true))}
  function handle(a,e,m){if(a==='service-tab'){state.serviceMode=e.dataset.mode;window.render();return}if(a==='open-procedure'){openOverlay(modal('procedure'));return}if(a==='open-product'){openOverlay(modal('product'));return}if(a==='edit-procedure'){openOverlay(modal('procedure',Number(e.dataset.index)));return}if(a==='edit-product'){openOverlay(modal('product',Number(e.dataset.index)));return}if(a==='delete-procedure'){state.procedures.splice(Number(e.dataset.index),1);localStorage.setItem('cobook_procedures',JSON.stringify(state.procedures));window.render();return}if(a==='delete-product'){state.products.splice(Number(e.dataset.index),1);localStorage.setItem('cobook_products',JSON.stringify(state.products));window.render();return}if(a==='add-price-variant'){const wrap=e.closest('[data-modal="service"]')?.querySelector('[data-procedure-prices]');if(!wrap)return;appendPriceVariant(wrap);return}if(a==='remove-price-variant'){e.closest('[data-price-variant]')?.remove();return}if(a==='price-type'){const b=e,m=b.closest('[data-price-variant]');if(!m)return;m.querySelectorAll('[data-price-type]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const type=b.dataset.priceType,to=m.querySelector('.price-to-field'),from=m.querySelector('[data-field="price-from"]')?.closest('.service-field');if(from)from.querySelector('span').textContent=type==='exact'?'Цена':'Цена от';if(to)to.hidden=type!=='range';const fields=m.querySelector('.price-fields');if(fields)fields.classList.toggle('range',type==='range');return}if(a==='save-service'&&m)return save(m)}
  function handleChange(target){const file=target.closest('[data-field="image-file"]');if(!file?.files?.[0])return;const reader=new FileReader();reader.onload=()=>{file.dataset.imageData=reader.result;const p=file.closest('[data-product-upload]')?.querySelector('.product-upload-preview');if(p)p.innerHTML=`<img src="${reader.result}" alt="">`};reader.readAsDataURL(file.files[0])}
  CoBook.modules.service={render,handle,handleChange};
})();