const DOCUMENT_TYPES=[{id:'pdn',name:'Политика и согласия ПДН',description:'Документы по обработке персональных данных'},{id:'mailing',name:'Согласия на рассылку',description:'Согласие на получение сообщений и рассылок'}];
const documentStoreKey='cobook_documents_v1';
function readDocuments(){try{return JSON.parse(localStorage.getItem(documentStoreKey)||'[]')}catch(_){return []}} function writeDocuments(v){localStorage.setItem(documentStoreKey,JSON.stringify(v))} function esc(v){return String(v||'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\\':'&#92;'}[c]))}
function documentCards(){const saved=readDocuments();return DOCUMENT_TYPES.map(type=>{const versions=saved.filter(x=>x.documentType===type.id).sort((a,b)=>b.version-a.version),current=versions[0];return `<article class="service-row document-card"><div class="document-card-main"><div class="document-icon">PDF</div><div class="document-info"><b>${type.name}</b><small>${type.description}</small>${current?`<span class="document-status">Версия ${current.version} · ${esc(current.date)}</span>`:'<span class="document-status empty-status">Документ не загружен</span>'}</div></div><div class="document-card-actions">${current?`<button class="document-secondary" data-action="document-history" data-document-type="${type.id}" type="button">История</button><button class="document-secondary" data-action="document-replace" data-document-type="${type.id}" type="button">Заменить PDF</button>`:`<button class="primary document-upload-button" data-action="document-add" data-document-type="${type.id}" type="button">Добавить PDF</button>`}</div></article>`}).join('')}
function documents(){return shell(`<section class="page-head"><div class="eyebrow">НАСТРОЙКИ · ДОКУМЕНТЫ</div><h1>Документы</h1><p>Здесь хранятся действующие документы и история их версий.</p></section><section class="service-list documents-list">${documentCards()}</section><button class="secondary full" data-action="document-new-type" type="button">Добавить другой документ</button><button class="section-back-button" data-action="navigate" data-page="settings" type="button">Назад</button>`)}
function documentUploadModal(typeId){const type=DOCUMENT_TYPES.find(x=>x.id===typeId);return `<div class="service-overlay" data-modal="document" data-document-type="${typeId}"><div class="service-sheet document-sheet"><div class="service-sheet-head"><b>${type?type.name:'Новый документ'}</b><button class="service-close" data-action="modal-close" type="button">×</button></div><label class="document-file-field"><input data-document-file type="file" accept="application/pdf"><span>Выбрать PDF-файл</span><small>Новая загрузка станет новой версией. Старые версии сохраняются.</small></label><button class="primary full" data-action="document-save" type="button">Сохранить PDF</button></div></div>`}
function documentHistory(typeId){const type=DOCUMENT_TYPES.find(x=>x.id===typeId),rows=readDocuments().filter(x=>x.documentType===typeId).sort((a,b)=>b.version-a.version);return `<div class="service-overlay" data-modal="document-history"><div class="service-sheet document-sheet"><div class="service-sheet-head"><b>История · ${type?type.name:'Документ'}</b><button class="service-close" data-action="modal-close" type="button">×</button></div><div class="document-history">${rows.length?rows.map(x=>`<div class="document-version"><span><b>Версия ${x.version}</b><small>${esc(x.date)} · ${esc(x.fileName)}</small></span><button class="document-secondary" data-action="document-open-version" data-document-id="${x.id}" type="button">Открыть</button></div>`).join(''):'<div class="empty">История пока пуста.</div>'}</div></div></div>`}
function saveDocumentFile(typeId,file){if(!file||file.type!=='application/pdf')return;const reader=new FileReader();reader.onload=()=>{const all=readDocuments(),versions=all.filter(x=>x.documentType===typeId),version=versions.length?Math.max(...versions.map(x=>x.version))+1:1;all.push({id:`doc_${Date.now()}`,documentType:typeId,version,fileName:file.name,date:new Intl.DateTimeFormat('ru-RU').format(new Date()),dataUrl:reader.result});writeDocuments(all);document.querySelector('[data-modal="document"]')?.remove();render()};reader.readAsDataURL(file)}
function handle(a,e,m){const typeId=e.dataset.documentType;if(a==='document-add'||a==='document-replace'){document.body.insertAdjacentHTML('beforeend',documentUploadModal(typeId));return}if(a==='document-history'){document.body.insertAdjacentHTML('beforeend',documentHistory(typeId));return}if(a==='document-open-version'){const item=readDocuments().find(x=>x.id===e.dataset.documentId);if(item?.dataUrl){const w=window.open();if(w){w.document.write(`<iframe class="document-open-frame" src="${item.dataUrl}" title="Документ"></iframe>`);w.document.close()}}return}if(a==='document-new-type')return alert('Дополнительные типы документов будут подключены отдельным этапом.');if(a==='document-save'&&m){const input=m.querySelector('[data-document-file]');return saveDocumentFile(m.dataset.documentType,input?.files?.[0])}}
document.addEventListener('change',e=>{const input=e.target.closest('[data-document-file]');if(!input)return;if(input.files?.[0])input.closest('.document-file-field').querySelector('span').textContent=input.files[0].name},true);
CoBook.modules.documents={render:documents,handle};